# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/maksimdrachov/pycyphal-demo/public_regulated_data_types/uavcan/register/385.List.1.0.dsdl
#
# Generated at:  2022-10-01 11:53:15.760115 UTC
# Is deprecated: no
# Fixed port ID: 385
# Full name:     uavcan.register.List
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.register


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class List_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     index: None | int | _np_.uint16 = None) -> None:
            """
            uavcan.register.List.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param index: saturated uint16 index
            """
            self._index: int

            self.index = index if index is not None else 0  # type: ignore

        @property
        def index(self) -> int:
            """
            saturated uint16 index
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._index

        @index.setter
        def index(self, x: int | _np_.uint16) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._index = x
            else:
                raise ValueError(f'index: value {x} is not in [0, 65535]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Issue110_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u16(max(min(self.index, 65535), 0))
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
                'Bad serialization of uavcan.register.List.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Issue110_) -> List_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "index"
            _f0_ = _des_.fetch_aligned_u16()
            self = List_1_0.Request(
                index=_f0_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
                'Bad deserialization of uavcan.register.List.Request.1.0'
            assert isinstance(self, List_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'index=%s' % self.index,
            ])
            return f'uavcan.register.List.Request.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 385
        _EXTENT_BYTES_ = 2

        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8D=Ii+0{?YXTWcIQ6kbzbl6BI?*z~1^Dlf%(=%l3-`qYOS0%dL2_!9C`gl2TS646LgUDi8+K>g6*fS?7R{?Pt|9__BXc7o?+'
            'BpsdaT)yw<kJW$vT^-E6{8iV>AWg*scrA>6BWeQ`Z(Q5Cpd(;@d=h<XV)Ag>cYxRU>=NJNZeHV7v}FG>iAf`D<zcKt1YhmbuR4a`'
            '6NHHQ0iS>m+F4YCyzz3ezQ)nYXz&g%F>i7aqt|tc5b!s=FQfl2VP1Qo!N_GMLoP)WJeKtCbML%vb<`8Ov3+KP9$S#V*a&0rcgx!3'
            'wT|3?9Y=+uCj{Pz5P9n)pxViwAKd^Iw`z}U2gO7M4gSPq%sV_pVWsf$Hqce7)mmQDR>BnXDwnRoJit_oynU;FUib5^zD32<R-kMo'
            'bRHTJLE`)TDL>a!ki2s~axL*NZ}H%gZ-5L2cqb@U-Y7q#Ys?Rih{WkpIlZRZR-RMy&ZsegXl=#opj+uhquhk{UElPb66PBTt;769'
            'mujOMPP8Ud!Y`Xl-s^MHiQXI9F>ihU;}3K4zpK8j3JDlXN4B{Vfl~8eV_{{Y8^9~|^wq)2U~sB*V2eX0jByu%MFp&(HFy>slR7kR'
            'Qr2`_niH5iFIU-3=)lB8Xj6!0&d%-?MDWA9XQW{-qPFAN`HTQ|Ui8Dxy=&PU@Qx)LwPC_CXuH_Yf-p+U1F4>LQVoZv<m<d7Nf8i*'
            'FIda)LCw=?g|@75wkRO73q_RN%4P<ctR;x*E+84Ki)@^PCr1ET>R!Ml+bChjbatWOc5&n)7im&FPYhK>S+ya0zP=fPr39(-@xwjl'
            'M?dShKii+sb}<C`6Ye_9>^_jtx3wc}5VZ%S6&kTfGyQ8<8twdYl-7AeEs&^w%AXwxDXG+tE~&j@Jxs<3-+yQ&go!W-@GsmQJ^4G-'
            '^qO>YARIkNHI>_HTc(s2Vp<j(Wl~A7#e2wM+6g;*a1K))>Qq<%0U5Py6Z`}K00'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     name: None | uavcan.register.Name_1_0 = None) -> None:
            """
            uavcan.register.List.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param name: uavcan.register.Name.1.0 name
            """
            self._name: uavcan.register.Name_1_0

            if name is None:
                self.name = uavcan.register.Name_1_0()
            elif isinstance(name, uavcan.register.Name_1_0):
                self.name = name
            else:
                raise ValueError(f'name: expected uavcan.register.Name_1_0 '
                                 f'got {type(name).__name__}')

        @property
        def name(self) -> uavcan.register.Name_1_0:
            """
            uavcan.register.Name.1.0 name
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._name

        @name.setter
        def name(self, x: uavcan.register.Name_1_0) -> None:
            if isinstance(x, uavcan.register.Name_1_0):
                self._name = x
            else:
                raise ValueError(f'name: expected uavcan.register.Name_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Issue110_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.name._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 2048, \
                'Bad serialization of uavcan.register.List.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Issue110_) -> List_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f1_ holds the value of "name"
            _des_.pad_to_alignment(8)
            _f1_ = uavcan.register.Name_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = List_1_0.Response(
                name=_f1_)
            _des_.pad_to_alignment(8)
            assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 2048, \
                'Bad deserialization of uavcan.register.List.Response.1.0'
            assert isinstance(self, List_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'name=%s' % self.name,
            ])
            return f'uavcan.register.List.Response.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 385
        _EXTENT_BYTES_ = 256

        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8D=Ii+0{?YX-)|f>5WYZ?yV8adQm6z1RtUirH46w36$sQ)QGu=rQQDM(s9f)Qa$~Y<uWaw>76fV^K#gRHN-_T{Z!o^SYjRER'
            '9&T;Vcz%4}e15R}&(+n=<mcb28ev6|G7CoXLjKCL0#cUiveH&M2!8FBGj;B21Gk$B!cn;NF#I0+euXJslKqXEk8-Y314C&YnDi!n'
            '(p|8XR+j8NHUeX%RslP{duO^n3WKFV=dbWE__K^VXJl48u;E@<RMHct;8$))D8z9oFEGI!XD-%<&$WlR;x9a1*>)@#yLe`n8_(Sf'
            '_|o*khJSrQW@C60{KY$*PU++(sG-Aa@pK-NH3kKgpj=zZqE0F!OX=i@JT~@}l|u#MJLO;qW<K6omPyBoNxCrTQJ*=tj+I(a8*lqp'
            'cV>a&we&jKwxWr!?fe;bgTKJ6<4SNNP6m2ZXZ{RDs(3D469)hJm!~GSA90=H_|6oT_Xa)e<NJf97!o(*?PZn~Hu!gE?HvcFPTkY{'
            ';Lm+6T?^VR+D_Z^&of;GpDYSun=;dd%n76|C^doSXmGx-z;LI{F-WT{M@iFwU-(z9Yn5{c>Y1*w>F8-d(U|qg|NM4c6x=kYJXhI>'
            '7d3>xLx0eFY%~0F3dU8sb#a%gA?!j0PA)3xfR%hq(9(r(Cx<wg#hTz(N<}2a1-Whg+x6YZYF%)09V|uH&SOh_!?@yVBAD$u11jVP'
            'V&m>sr-whDaKxX<8Y9!tFSn{(W<nEmols}oZ=6sV%bHfWR1?G3EDf1}%0R?TghT%#4Z#=$tF&=Uim>h1nboz)feZz(iqi=BZu}H7'
            'BT#qfofz-L(<5qq=>wAI9?d(=$6Cn`tSp7$IqDJZt0r$M<i(~SLIcUI&WK<}`lQY&{jrSc_G+tMdO&9Sr3g{M=||~@X`Gqh;*f7J'
            '<d(`ZQFoMhBy$Ldc;CNyO(lD`Z(P{~m6I$)GK-VM{?mY;;Abs2pU?4oeuoPo)$kOrWc`Ysv#K?dAnSQPPSZeD{Pay(xn`0wk&0?)'
            '-^HW^A~tcz9sNa<fN>&iqHCAv{Up=1683T;Q%El-LfTx@GulLteW|2H5NYHVGs^n_*DZ=egl*hM*~ee-01GTpp~lLue|+WB_EDY#'
            '4&5WXkNnvv{Ptuu#y=J}n*I;VwL=9<1^@s'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'uavcan.register.List.1.0()'


    _FIXED_PORT_ID_ = 385
    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8D=Ii+0{?|pZEqYk5Wa|{xm=r)kiLKltq~9oXtyn;Q1K$vR;_?*LdZ*1RVpj*+PSg1YcIC<nyXZaegLJCC5mD`@P%K1K>Rzt'
        'mGSOfa!C_<U(WV;9?#4(^W6P7{@WK*jq2mh6n$n`7R82ZK{N4?CK-?7RON*-!gB8puW;QHDPQdu+;92!9{WeW?WSYRe<-=Ju?^?Y'
        'aMLSRm#HoFo|_Y~q&eceUeaDlWu$pm7|V5Z3%{b}8pXS2+~e8^B?H#v?ZJA>cg8x6pZ#NuBc|4Bk(8Djf6pHj`SvC6CT<Fzv7Ja-'
        'F{75&0UzXEXpsvmdU#`QO&ZaaoP8}V?{d96t;2C5Y@Bh~wctB52%b``My?oE<283;X$TbDqU&f|2qsLZ@snTn?pSOrm5gdO3ba`!'
        '&~g((GQQ#6c+6DlUBj0Nb#o*6$4S4g>LU;DzzKuVFkWb$Qp=ft;*Q4aVuQ1|P};_V`9(Jy8&&F*qaovQLGdj&8NM=+csI3#WN$2m'
        '(=E(x>^v544GUwuo6hNdBXXu`3aW?uqM!B)pxHUbbLHKsqD(T8VmoxpEIhwcWb{5%laBNbY4>jS(v{0K`4^)LQ6RzFP?5P9sKL-Q'
        'mo~5xn$B;+{GEldMq?F(A%jCgvrIiO!~!QNuDK>w5hhHkdSQ*np*V)9^>CF8pEiW{sK^4*M9J!2K;*iW^a=L5rdG&qbzTub)<gf0'
        'b**ypkZVOsX+=h;Bs?!{zj}mVSej$kW1mE=)++ic&9J2q2%isFJI@=a!^x?TBvmqWfF%zADH(~Tf-I#(h-fz;8l<wMTT+dVoU@Sk'
        '0IrlNP}#+^2f#;@Ll-s(6W`OwP!u{V$&jA;;SlV!AXeV)-FtWBny|O3{R(aeL*QPDRpA{u2*mXBL}70rwF}rQIARuO`r9HDTIrop'
        'Iuxf^0_NemdwGd6hN(Vx3BC%}#WKsN?(elCLXT!8_rLgdXXdF%P)&*&$ak7$g6ZZ$hAG7b-3W`xFsazE!Mhdnje^Qba2CtNB<OJz'
        '8`=~|5g!QL<RFfgd*c8htFL=F0y8js&%^P7$Ezd0$M*UzhABpuqeGqB?TX{IzshM%``(?rP4N^@YHqHE)4e*)GoFWus?#_%KtA1R'
        '!WnoA-bTf7Q>a}9O@;0I&NKJQki@F}_w{?TGZsXw@`lgh%gPAX;Km49$FD0H^hoZ@dU!LCj>C>(-iE~*;=90L6B*nEb#gg$_A)QH'
        '6$iD@{hHZl=&%<HV_fYtU~S>wNx1z8e^G*=@zlT_WSg5{ZKAc&eBN3)x7>IowlELxq7p+J!GDEy1Mfe94;JApoNvPgxCkG@CHM#~'
        '!^dtq(7IdR;L|5C?@nKpWNr24m2+ICIF@W%94ax1{QkxKW_z^(E1{uxMZ902?(U5diIQa4%p~X7=%^0Vj_4eUgDP#%t3;KOnX^Ph'
        'JUY8Asr_(cT}WXdsK>Adf57(#*8o1Lv)&9<dr?}yzaXt+`;FZ8q_syzt%<iM2Y*clgpFA5qP3~FC$%#3kV_l>f<NIO_`9qUT6jG6'
        'KPe%R@L8Ee{{aQxV*E%6000'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
