# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2022-10-01 11:53:16.316341 UTC
# Namespace:     uavcan.si.sample

# There are no data types in this namespace. There may be data types in nested namespaces.
