# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2022-10-01 12:13:28.307353 UTC
# Namespace:     uavcan.si.sample

# There are no data types in this namespace. There may be data types in nested namespaces.
