# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2022-10-01 12:13:28.407656 UTC
# Namespace:     uavcan.si.sample.volume

from uavcan.si.sample.volume.Scalar_1_0 import Scalar_1_0 as Scalar_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
