# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/maksimdrachov/pycyphal-demo/public_regulated_data_types/uavcan/primitive/Empty.1.0.dsdl
#
# Generated at:  2022-10-01 12:13:28.544022 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.primitive.Empty
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Empty_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self) -> None:
        """
        uavcan.primitive.Empty.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        """
        pass

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        assert 0 <= (_ser_.current_bit_length - _base_offset_) <= 0, \
            'Bad serialization of uavcan.primitive.Empty.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> Empty_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        self = Empty_1_0(
                )
        _des_.pad_to_alignment(8)
        assert 0 <= (_des_.consumed_bit_length - _base_offset_) <= 0, \
            'Bad deserialization of uavcan.primitive.Empty.1.0'
        assert isinstance(self, Empty_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
        ])
        return f'uavcan.primitive.Empty.1.0({_o_0_})'

    _EXTENT_BYTES_ = 0

    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8=q@;80{?ZATWeG?5XVoo?bchR2)_8BPf`U>^(z#7+PW@QeUp&OxF?vLgj^1Lgo1q$gn+`1AHr|xWVc?Zn3v2yGnve9CZD#y'
        '|G3huSGn&;6_sgOgrK?6AGt8lGU=>$Q76E1>okQdQx5QY^nfdTbdG0uSaw*?E&1<eK1klTK4`0x9-w`0eHyXsu>nHVuE(w^leZW4'
        '3a4As<};pSxxsi!L5rLq;yWyN{?bg0oBU@rPJs^~c>;xB%07Fqm!Oz;Au+9RRt{KnIY=Of0p@w?uuSS^w7_z0P9)2DJzY`VTSr)S'
        '-VkmiHp@RmZB^j1a|3BV%F%b+JW*gBmU})6qa_Ql$fiEe6i=KbY6RWh-H_7@zuB?uuj$)o?bEh478AazWF3!GSb#p&P7hiFk!&;N'
        'B$fur5{5E9{51`s6En~+Qb*zGvc_`rSf`V<J|%fElX8_gkLAJtlEl#pM>tf^3&NvWCz{Ah4}m8a{!Dh4$xa)E-Q#k5&Xv;r;-8@I'
        'sCsAF7#_yUUdk|VlL5ct;k5Y{1^orTNrcnAEC|=?9;Zz;__7)kW}TuQ*W1?_EIsen-({9X6j`)C0e>qDm$U)^00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
