# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2022-10-01 12:13:25.737572 UTC
# Namespace:     sirius_cyber_corp

from sirius_cyber_corp.PerformLinearLeastSquaresFit_1_0 import PerformLinearLeastSquaresFit_1_0 as PerformLinearLeastSquaresFit_1_0
from sirius_cyber_corp.PointXY_1_0 import PointXY_1_0 as PointXY_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
PerformLinearLeastSquaresFit_1 = PerformLinearLeastSquaresFit_1_0
PointXY_1 = PointXY_1_0
