# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2022-10-01 11:53:16.513705 UTC
# Namespace:     uavcan.internet

# There are no data types in this namespace. There may be data types in nested namespaces.
