# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/maksimdrachov/pycyphal-demo/public_regulated_data_types/uavcan/time/510.GetSynchronizationMasterInfo.0.1.dsdl
#
# Generated at:  2022-10-01 12:13:28.441880 UTC
# Is deprecated: no
# Fixed port ID: 510
# Full name:     uavcan.time.GetSynchronizationMasterInfo
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.time


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class GetSynchronizationMasterInfo_0_1:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self) -> None:
            """
            uavcan.time.GetSynchronizationMasterInfo.Request.0.1
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            """
            pass

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Issue110_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            assert 0 <= (_ser_.current_bit_length - _base_offset_) <= 0, \
                'Bad serialization of uavcan.time.GetSynchronizationMasterInfo.Request.0.1'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Issue110_) -> GetSynchronizationMasterInfo_0_1.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            self = GetSynchronizationMasterInfo_0_1.Request(
                    )
            _des_.pad_to_alignment(8)
            assert 0 <= (_des_.consumed_bit_length - _base_offset_) <= 0, \
                'Bad deserialization of uavcan.time.GetSynchronizationMasterInfo.Request.0.1'
            assert isinstance(self, GetSynchronizationMasterInfo_0_1.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
            ])
            return f'uavcan.time.GetSynchronizationMasterInfo.Request.0.1({_o_0_})'

        _FIXED_PORT_ID_ = 510
        _EXTENT_BYTES_ = 48

        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8=q@;80{?wfU2hyU6x~3Yq?;C6m8OUSHApR65vGX*FGxuA1EFY18YL9*Qdyqy&Dz9c54LBML5kEqfKtg4m15rcf&2)rXEv~#'
            'HeKy%#(RCwz31GIXY+skv(Rfl;a1gf$5lohSjm+9jpYh5T9~pjPI`#p@*_~P#8>`fQ$ak5cb~_jI0y?=Y7I7uUbwvLZC&`<!t9j`'
            'RI?Hx)@n8`n9jT`A^RTuZleofjmBtR8okM!2fLy7Otu5R*5G^$OLPp@p)uhv{xo?%iNoG-?vMC9hGojUw=%CixcD@NYg1>MH(lhT'
            'bdN)2p<qZLz6kHoJ$VS6R>pcNdE5$DsWY`L01XOg#k`1NF+G&bW4O4DG8}HFe@~Fn+`SksJVC7-3RALuCrfTwA<P)hRZ}#TVCoAF'
            'rHSEYRp&|;)WWD%DLm!OGwM+y^j_#RiD5pe62slE*4N&w&04merCLQFcM@O09HwhQ`&7KKEFd0-dCE-@e}4b1Uhg|pup!!TAYL#}'
            'Sm7OE_$4VKakGI)*+yC=#uDjB!K%~=#Ox(MsYl7v)rDB?J7H?Y@lYiZ5gV^h63F@+7{lbh0Q!s}0eM3zYsM0@kjTQ8T{M=P+LHqz'
            '3vrqbhA-RDwN0c{Luv;cy)Xn24gSE`{jA@AtPA*`#D8AGIMAy^ddyvG<4F$qC(|Ruz}%JTIG_*;kSZ}6I&sWQfP`ght&uXa(Zrz5'
            '60~r)+TNRv`)VX)q~I)`slYPdBHq_TmKC-|Cj-jc>X(E{HInHJ7Wv`N0<Se^+P|q_T~-ZYN)d<6r~0T`n}EX!n8}u@1J<|<TaM-m'
            'Tky{5?B~)`1$yKKc9K7Pj^WY+>3?X?yLg<8cX*qcDh6^Mh-=E+AW>}9O`L~G){k2$jGf*i1!~5lxEJ2tW}Kr;uUryeChJzM6tm4)'
            'D<X`Usv-Uv2gBY=m*euNI-odQs&k}UN{yQ%y|BadvPetAaVV2_pTc3qbh}@+>fGgZF8X3wToPBr)u&NhJBs4^3$d~#Zio*C;->ge'
            'd?Y>=w*(QNh)>fjirdHHj`$2w;m~8}#?5DQVFmY2w>K>nz&JkA<j3<iZe`PD92(T?31&0Wz&Esq5!l(Kx;&+H91_gGz(z=fAc|pF'
            '***nIZrMY$Z6*`0&bi;y;&_ib&#<j5p9VTc)&uc*8$)DbeM<N14~<UiQ@^%=;bK=m99dk$1MzhS@l7fQ!D7rn-PlP}vI7-(d0sc{'
            'cSTx5hiR;(mu+Rf-4gdvUh&`vYda~pc!YHWH!=SG8e?+J{spRay-W87000'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     error_variance: None | int | float | _np_.float32 = None,
                     time_system:    None | uavcan.time.TimeSystem_0_1 = None,
                     tai_info:       None | uavcan.time.TAIInfo_0_1 = None) -> None:
            """
            uavcan.time.GetSynchronizationMasterInfo.Response.0.1
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param error_variance: saturated float32 error_variance
            :param time_system:    uavcan.time.TimeSystem.0.1 time_system
            :param tai_info:       uavcan.time.TAIInfo.0.1 tai_info
            """
            self._error_variance: float
            self._time_system:    uavcan.time.TimeSystem_0_1
            self._tai_info:       uavcan.time.TAIInfo_0_1

            self.error_variance = error_variance if error_variance is not None else 0.0  # type: ignore

            if time_system is None:
                self.time_system = uavcan.time.TimeSystem_0_1()
            elif isinstance(time_system, uavcan.time.TimeSystem_0_1):
                self.time_system = time_system
            else:
                raise ValueError(f'time_system: expected uavcan.time.TimeSystem_0_1 '
                                 f'got {type(time_system).__name__}')

            if tai_info is None:
                self.tai_info = uavcan.time.TAIInfo_0_1()
            elif isinstance(tai_info, uavcan.time.TAIInfo_0_1):
                self.tai_info = tai_info
            else:
                raise ValueError(f'tai_info: expected uavcan.time.TAIInfo_0_1 '
                                 f'got {type(tai_info).__name__}')

        @property
        def error_variance(self) -> float:
            """
            saturated float32 error_variance
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._error_variance

        @error_variance.setter
        def error_variance(self, x: int | float | _np_.float32) -> None:
            """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
            x = float(x)
            in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
            if in_range or not _np_.isfinite(x):
                self._error_variance = x
            else:
                raise ValueError(f'error_variance: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

        @property
        def time_system(self) -> uavcan.time.TimeSystem_0_1:
            """
            uavcan.time.TimeSystem.0.1 time_system
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._time_system

        @time_system.setter
        def time_system(self, x: uavcan.time.TimeSystem_0_1) -> None:
            if isinstance(x, uavcan.time.TimeSystem_0_1):
                self._time_system = x
            else:
                raise ValueError(f'time_system: expected uavcan.time.TimeSystem_0_1 got {type(x).__name__}')

        @property
        def tai_info(self) -> uavcan.time.TAIInfo_0_1:
            """
            uavcan.time.TAIInfo.0.1 tai_info
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._tai_info

        @tai_info.setter
        def tai_info(self, x: uavcan.time.TAIInfo_0_1) -> None:
            if isinstance(x, uavcan.time.TAIInfo_0_1):
                self._tai_info = x
            else:
                raise ValueError(f'tai_info: expected uavcan.time.TAIInfo_0_1 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Issue110_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            if _np_.isfinite(self.error_variance):
                if self.error_variance > 340282346638528859811704183484516925440.0:
                    _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
                elif self.error_variance < -340282346638528859811704183484516925440.0:
                    _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
                else:
                    _ser_.add_aligned_f32(self.error_variance)
            else:
                _ser_.add_aligned_f32(self.error_variance)
            _ser_.pad_to_alignment(8)
            self.time_system._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.tai_info._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 56 <= (_ser_.current_bit_length - _base_offset_) <= 56, \
                'Bad serialization of uavcan.time.GetSynchronizationMasterInfo.Response.0.1'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Issue110_) -> GetSynchronizationMasterInfo_0_1.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "error_variance"
            _f0_ = _des_.fetch_aligned_f32()
            # Temporary _f1_ holds the value of "time_system"
            _des_.pad_to_alignment(8)
            _f1_ = uavcan.time.TimeSystem_0_1._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f2_ holds the value of "tai_info"
            _des_.pad_to_alignment(8)
            _f2_ = uavcan.time.TAIInfo_0_1._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = GetSynchronizationMasterInfo_0_1.Response(
                error_variance=_f0_,
                time_system=_f1_,
                tai_info=_f2_)
            _des_.pad_to_alignment(8)
            assert 56 <= (_des_.consumed_bit_length - _base_offset_) <= 56, \
                'Bad deserialization of uavcan.time.GetSynchronizationMasterInfo.Response.0.1'
            assert isinstance(self, GetSynchronizationMasterInfo_0_1.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'error_variance=%s' % self.error_variance,
                'time_system=%s' % self.time_system,
                'tai_info=%s' % self.tai_info,
            ])
            return f'uavcan.time.GetSynchronizationMasterInfo.Response.0.1({_o_0_})'

        _FIXED_PORT_ID_ = 510
        _EXTENT_BYTES_ = 192

        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8=q@;80{^vG-EUk+6?f9Kac`Q?Ds4!GphH2_Ro9!{_18Lx57&vK#qrv*owfpntJ!<Uo~iHNxt*Eo%~nBBP^$!8Xhd!W>LU+`'
            '2j2RCc;f-_gv1|!#4G;>=gjQKtYaq>!OF?rJu`FW%=!48-`t;^`Q)?9Q}$E5lJ#R9C)H3hC1@hvr=5gV!$@{BsfA%>asC=hL>C_8'
            '-G0W(hvn-Zls_tGif2NRrc9N5syM%6R34dJvB@b<hbirXih52DBbru?=(6e!W_J2%#Fb28HzQ=aLA7D3mF~&vHq)6*HLRHq51G<1'
            'iW{7LYw-NAT%TG$^-=jjS)2>0F-mlD!*qEYc01uHqgiF~^qOEvJhm?gV`^w<(CCwvX9^E54q?W#Yl)<0@`&fcjxb@u(tX3rbpk3Q'
            'I8E4<F)R7Y#igy`a$Htjg|Q7B!gG9BZkNT2p*A#)sfv9?_drjV?x(`!F>bu4XoQ~9;Fq<*Gw3K@o13pSnvJ>n#l^YiLZjJSSZ>zq'
            'OSSoWb8fylzffOXZY<2t*Gk+g@9?0wz?70IJfv{OGy>gc!dOP-JM*WfrhcGVB-8kZjoZO>oJEGSDnz7YI9MTaj~LDfMiZtaIU|Z?'
            'QbC50P9KJZCS4oSYOsqx+#GnINg{hN%SaM&n(i~Qrx;86q{l_VtWviSC#yV7MY>-N*1!^Whjz0B4cYUiy{3umr6fvZbbw3rD6e3X'
            'o-mwHa-+SoQ?YB<#F=nDyOXiVID<qQDMmF5DCiOUDNW#15zElkBxbOikcvXCRY}X)Fqj2;5~)qa9ei|FU-!O}Jpu;PSR{RC45|W0'
            '1~>$E_GF%b_ZaMyu{36>A+Rk@d@qMwH2n#uA261IYY2z5=~2Z9J)|PRd<9b?@N%EbbZ9&t?_=KUV9z<%?fH6@Y@#0~kD}N<6)B4+'
            'j^nJ0mCQ(of~(<3sq6|^QpK!#$<+eC%+C&<g5r{2^1JZgP9OH}mi#$>VOYZa1t?o@^~=S@TPd2t;#O+dK2sC5#=o+DhQGqUx_%0?'
            'nScGhP3Whsi6x&crqGs)#q=uF3DlGsFTBjJPN?|WaPf;9o9)fr&30=w+-bE}uZM4LZtkKkwjon#Ad@2JaV^kQ9VtyUI5LEJ?Vc3d'
            'V~RPSQbS_Nbo!bZrn-x`g48{LFfp3xY6&3f%rCw?L?6f-#WaH51oljCTd1VT@Kn6TXNps<vULYe^X8Kd`_%4A3(oe=Ur$X<p?_66'
            'P)Sw{L^C27rf(8%Os211xx&(FPaKGh#e!C)+P{Lou1qWp-NFzTVy(OM1m}0NLFNEt7|17Wvn<WK9Y{aOWLTu60~Dx~1bhL7;(T0R'
            'UaHO3>hQN)t6jB!-zQ)>=wE3$5b4oA`g~8^fmOm~il=<2mvSgL6x`U_v4&LxmxS8IC)aE=L?~(;2T*gH@}LO1ka6=N>(K;&I2y-T'
            'et0HlL@f3OE33gsCD;myLUf)Dz;O?vj~D~_iDrRvEx?{M0*&YoJ<?-{?Y`h-+(!?rhCV@PmL(#x{)ha5B)I8iL;Z7P!;33hTQ^&)'
            'E4!`DcDS>3eYLgLTE)~~S{ZLKs{zEs-lz(!A!vJ^9;67p8DIi9NU%qYIbB~ES;LBpUb7B6ea8#Xs_*b6euJ;_xA-=v{B{lv6(A6h'
            '7pf&L?-v(B>){Yx7>c-T7cYcb<|<+^kgzbL&@PL!_?3tbw8|}T+?_3yK7{ss>I!uIThP&=bDoFF)1n(g|K#!zerNrtpK+SZ#;hyL'
            ';!9cHfrEztfq8=4kJ$mNe#QYBG)#0wSzH{0TD4ZKSFw6agDw4H$f*XyFpfwj4h8ht`{3DM?0QaQkg!ZyFON%SIH<v@1lxfHXYiHH'
            '9hAAor?Da1l47PO)j>6A0nX4A^9@!x#EHGOI+*A8Rc!s81WxviA@qz12$*e-{w|B>-W2Ah{k_9R=vq7#%B(ENNlJ9T+mYZ_@XH3c'
            'c|iF#Gd#OgKAnuf+PLIDE55Mh3ha?d{2q?B^CY3Fe{__$J}zh0&pgl_;EtKoP_9qs9XKcSDtN>PdIulQB0+;7qx}IwE=?`HZ08+Y'
            'Jwb5}!x8F1)0!=A`>~61g~5e33t>PQv9yPcSkLNz771xjU}JGY7ri*qMORwLkssSa$HgA_#eR7VP$A$k`Xkq2ZX)al|2i`@g$Xz~'
            'l?P^U0@GtGwYZ1qb8C0iQZQTmmIw`ipaQ6C5%PVeWHs=4UzhfWEf6{b)c;7UgAmj^gp<ecz)Ik#5dtDmBVhm!JHk>U*j9G1%@8F!'
            'xi)TN4dhZno!zkwD<KXw^ohoq9@Hr`fj*<Eg7~XNXM&mzf<HFtNxkwWH2KhVBWOKhNVb$TwgwPKuTur=4^+m$HIqR)OmHu>P^MrA'
            'WRq(OhpbAjN!wd6_hfFgh?!Fbr(3gKW)Q&&;qZVP*k%QlLlWpYxHVv`R59cx1a}q!>&M+Wu!7$LdX5=WPgvMf0<F9n1Oz_Ukk;Vm'
            '?s19+SBl#>b$0Z*JNvkgRr@`fA{A(W+Ir1N@?<2b`*Y?{((onoD4Fvm3n-cQC5tFo@FhzqS@b1Mlq~s@Wt22MNwbEMWzWK99V89k'
            '<|f+QsQVJMxzX??Xko**xrw_se4CeXuZC~)vfXRZ)3a>%TJj}!ucj|S|1_3;J?M=&-{xiX#+>ixWjy=b*w2kx&90jBC3epINKd0y'
            'M|<WLd<mX(ZqZv+w|gxG!HVTYjas8t8RRRzQy5--kTVa+odpeBOF$lNEe$aR^A86Ru@viC?wLa-D#Qniv&S)`X$O|~99Uj!t*u?('
            'zK-_+P!n#n+P8K>pmo>>{xr(y-DB9FcTtAwIf|Ym9t!2l9620d4?D!R@xNxLLi@z@5q`G(c(ypvK*+H^0cVG|+UxDjx7*+w{@o*V'
            'bbL8soTJj;@!#@4@Za-4^3QVq?tOmH<_VWGJmc?i#WgoP=ZD4fgGM(=tN8msq25VPW3R%40W~9*ngMj~!Hrd0K8^Q2N0b4h$1f-}'
            '$y^3l$4HwxCtiUnK(w?Rb|>vFA3Kcw_ctS(E5lUPTx6rvu(-+<L!5sXfZHR18UPdbu3#EehV2)HcnN~;Ch={GwlIv5|CUXcH=t67'
            '88{lib#IWHcC<Dc4c@lB;nkZvuMQi;kOGV^Q(n>OtDmRe1*?`@Ph41riEI0r!WTc%RY#Ar6l(yod_R#LSmv`~yht$yt!naerHzv5'
            'J}8NWj-a{I{r}G$>n{JXOX{EU4@W%o=cA`zdh9a*_Q`*Rq?12ff1a1{?-LmN^_W*qBmEMV#?2P#N@Q|;?*hM7*8v&rKts1qfxFeA'
            'h#z^WW(nBnQdu3~5We4Wmjb^y2)_K0nafE;zd<2Z_$B@ueue*yfBKk0e0`x_d;II#BNckjg1{5}^`Xb*Us{zZ-t^LAF9pT3?oI%~'
            '!WX<x(Do0v=|4}J>BouqaU%HQb`&T65z{E00qM+GI-Gn&{1-R53DV}HlPAS41Nb@M@6S8lehEVG>E{Uv|GVdCxWyp3O-;Em^-OUI'
            '?#=E!y$bQg2YlK0+8&}4K=g0BE_ZB<d=Eb2EkA5u+{Ui84Sd{)lWubd?ymLcBc7jrVBPSr&CzP~&H6OTrygkQB<oKcB*zTm((1nf'
            'FcsJaz8C-i'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.time.GetSynchronizationMasterInfo.0.1()'


    _FIXED_PORT_ID_ = 510
    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8=q@;80{^vHO^h5z6<#}zy`KCza$+Jvl*T~3$&SY}vp=47gwT4uYYpq2U3S-rmB_Sux@)(}?&<3E&(2O1qeKW~OC1s9=EQ*r'
        '4jedf;DE#-CypFZjvNq3+&FMWe6Omzr)U3S6BzBzcE756_3G7o-}|ce!xKO2zcQvi$*car2_3g)hAa@4E8e%dE~}Zg?D;Yj5lfS&'
        'HdwGDY_>V@S^6-2{iF0=I*~kM2JF3<g^?MNoR1~XTw|{2VTd!@^Q0*}j|HmBMij($6bE~hJ!yJY4^!1+Ysa>{S|oa`cAZ5V1JCAx'
        '^k7vaq_<*)5ewShmaMJo$<t)q++jh8M$&)kt?c<>x;(ag?8oUxFyFMIC=lH^VqtnaP0p6y&F(<Ye2@A$%nz7tVFBrb<XLk|>@vsn'
        'We}OdNju5&W+>ypW@vDk>01#`lT-A^72PyBy#{yfu95U1R&?xAnml<EJ`L04nVxkw6g?-fY%X{3?hovN&n@?&!+J7JUiRazD{MG)'
        'J9cS$)3G8;`4yv2YM-RZ3Gzysygt*YAMKlZtx=;rO`~+3*2}FB<_64*Xp?Cx)BDK@(~)+1>!sskV~g<M!0@EQjEGy2VcAh=Sokq$'
        'Mk5@Z$mpq=s)h^<5gNATQ^Xi@i^d6Wn?{DQ&8wA=%h+}B;*%4h8{IPlYLzzTkli~BV|ExRilpHOa!0@lfmH-OJ)6~)ab)zluz79{'
        'rthh#<A4_B4vaWt4n|=LW_T>>%iwOUQd#wEHe5t8ip!9BRYOFu-ScE*bQy$}w+$Vz-IaO`aD>aSR6}}9J4cR8K)Qn1^RQ&B#xo?^'
        '0s}2hSXKSX^X{JsD{|RhebQ%v6)BDLo*{ZZ!a}<N?p6LHN6{V$dS?OFhu?rXvFBJ`bkv4vs|JSUx<-iLb1U$gG9W|-j96>AeQOZb'
        '5OQYMMF_r@V?<X(rpvtTh$E7sz3*xA^i>hvQ12Uf&C)x0!jyiR7>6kd2fePuLJ_Jf$cN18Rpkm9lySs{&zzJ`C(o@}jsrLC>%`}%'
        'wG+Fp6%6*aLc@;b#w`6wI<Y+VN!SH=_*zlAJRWzk+@A1&9Q0uA(!(jUCmkdujjot%*S9={FP*p>cH=I8j-TPr^B4KK+bMtPUdq4v'
        'fWO?~U*oS%aD#uHpXcA;-{jxoukj0%i~NoIe3Dn8mF-4|+;ru`W63$-j>gTv<jivLM<MEA$m|Ey8A$_w-GnvU9&_4W#I{*53aU?)'
        'Je@8Zu-`@?(1HNhYstB_ToDbcEud|MngE^0eni0Wf*D2@!YXjeitc087kORH!Ke6a$?q>NNRQytJ8%P&(|Z4qvVh?U{vEC2Ds6^='
        '%@|Sjm37LJb>_2392O0C^(NIZpsZ{B6SXso9liwj^6U4ox7mjCHujB$S>vY%G}2H&f51XtdLhed+o{a53V%9#dM;@^Myb-u(mYZo'
        '4%^zIFrjuV35HlNmRlLt1lqjQORlt{k^Sa3mks_FzqLF@yT{+Xk1;)K+Y?cYT}@7J1%%Hq1T}Lhd&c18!qjxV*=kNr&(2P@W}2<m'
        '%v`I{xLluZw5Fz8(=(0Px#rCDbUh`t6!OWlEC^(PT!QU@*pyG+nnoFUH)OW-obNYpR~D&*k$0#PH0O;~4P_bNsC)!|QGoy`b_W{e'
        'G-A~%oAjdl-~pH=`{;#Ap;6S>3K#?Y53y7a9D(K~Si*KKU?~~0RqA#DfZO*B+m*IL-yv=iK8uK>cwFynY-l)VBWt4mfCH2-ZIJNn'
        '0M&w3sQMu%Ef=e@nXdrYVVF%wL@*0$MqAsE^%7KZ!l<ejUaYmOdpnSQ0|r};a0l8LQUym=s0nuVRiQ<70fk|n18B*M)q63*D;kVA'
        '{VroZ6>5&u?o<7+b}ZqlDh^k`%L8MgYdORA0mWii+0xF{bG}|PRDB&?3Mh;v07xUt(bhSE^o_0sS7S+@1kze=jRNY!EPj7j%C2+e'
        '?ApZFhN?`ILT7Vkr&6gjdcDYl6Uc*i_`45Ov_7dZpHC)ZG}{l7aljNITQp3ay@Ma*gI`!#?W}IDcG?T(M!U1HXkJ}i-6UOXMWUc1'
        'R_v^D3UWqQ%BWV^(<BNe6|gOoZ0$AFa7VJxyAb8UtoJlPaNcD^J$zJPel>X|#|nf5aEZ##ND&xcSAb)=`EvMG{&8|l=c|IkUw+Xl'
        'pV*vlQx^a6*w`4AlEBMU8uJl0$~I^R-ZXd=`QepImzY=Ui@U;Sj<9Mn*uF$>mqrGfdZ0-IDUEgH!RtLg3ksk?gir}J1&VuJL>7V+'
        'g953s0!iS)3CIEM+{WDH`o($!Kb!UX74`Fu0n4F(zOC_rXbYUJm^)HZ6~&VBT(3oSmIT+=Hk4ttijJ?0ToEzKn=}y~?p#J{p$M!w'
        '()|(8WCGAjvkA2(ZG<DXvXQk)p%S(d8_b9?dV%g51Rn@YG7HK>0ed_f8p$7Fp(irbu?$Y8dBV(Ulxf5A3$~~NhySJ&4UNZ$h8O17'
        ')^4;H<~Q4`9dl!CaiP7`UZ9x2JU^V`VhDT^TSfS5;t1Pg@2*Fv3NDYD9SOG2nB$F^!Wu@bX@dWP|D6At|BC;P|CWEo{}3O_qmr{j'
        'Fc>}O@HZa7#E&;i)-de6;?u~OA_ntDMS%%23kFP^K(dT3?>kSlqerFjdF@FLW=d}sPi5Y6f;iAM;-P$Td7Lld7xbiHCD@p!$bK`-'
        'kZ>}&U0&?)Fa*0PfK@GJMJZi)+!M%Q(0q0Tn&;cZaUKzuE9EeIX_y)&kbtOn9GY=t6B7OX#Ml_^ShlKC8es)dpD|Bm9L4?3%>`B0'
        'RoJQOnuTB$`L1&FeHKU@2TNq4XAN@H1ty^?7g}}jlHNR!k02M-imtbmim11Oj?G=6>Mf>~T>>~Gklh%kNHuW?#v&1zy9z3C4pSEj'
        ';i1MweW8x917_jCjm!^4cZBZ@kF}XeUxd;(P*+Tig8)5|SMWea#W{1)3P35K(gA^Svv3$G=wzYvU<jf~!_f|_8P}vjHHtkP*+V+W'
        'D^*zClESxa2djoUxC#yZTR5v3uAp=F7EvagpAnnb+>6-Q^1f>aR_U*B=yYE284T<Pf~>q!sTlZNqe@Dj4-Qh4@zmSY^<we);Nnpq'
        'rS`j)M@6U!wT-%##BL#Jl>1DPq*<0slVqwanIXw^Su#tKnX=?ENoLEE7D+CbC37Tcl_ae?N#;rxwi=K$%Qm;j=4PWTA)A}cvV<&b'
        'mThj)?9H;xb2L}8Z1bF&Yqq3kPR(_>EKzf{$`bNVbFQq1yfIa_d5*j>Rrd27t$k|f=VraGMopC^s?T(xr&({1JySDf39WQ$wlu1t'
        '=DJ*|%&UsrtT*e`EMDpQGUwAo(=uA2KttscXp73F98)O%sF4sWU_HfpVnkv<_@Hq1pqf0c!ScQa%WLhWrN#9{qM%S?uCzNhH%t%;'
        'ssq0-B6{-x-cdSzA$#_sXTgAwzD(1S413rPm5u*3FA`yy676FKb4T-(kpf~I=o2{GyxCdqtiIiWZ}_Ksh){hm_4q6Q3;zfI8~+#o'
        '=Ml8yOjhU);2gKS<5a6?VK|{1>ed#}xrJj;sF)lbH8e#7Mh{QDq2cQYP>zu*bPgroRWOrK=G7_Gw0DEC|DKbpSjj^*<iamPL*XjN'
        '$r?C+2f$roO(6i2=B`p0RP*vnLZNPqw<I0WLj}XM^WRqCGKoyhBd}<oag)Xk)mkrFD{rgXaQ?=|`Mf~n6ktf>OGy`Ad7OGzSy0#R'
        'BUCvLTvg8kx=oNeJNle?lmm$JZC7?NY|llq#~4c0D6J2pKziFy;)u{jaksYrKkWW7cx9!`E6;#ep4rPQ$BBLkMdKzDZ{Ch#I?V68'
        'gD0nCH}rdNY7_x0jx)6khv?Ekv*>bis2gkP>zE|;%M$UY{3HHn{_su(hfw}`{76@+pMH@ehB8ZcbBLRMxt{wjE_3G^aIR4}m;XuK'
        'G%im-Ix&>yokzuYj$_rje+vz*{ryM9+2!*G#g!tQ_mF@7rCixr89T{WOK5B8Ym`H8e9MkH;x^aKp5*dpM_kon?!&KYjgtpo)gpK&'
        '9`zn}c>P*Bn~X!lsq7z_s$7g5dUh!}g5vsCHES2&>A<yjZqV2F=xY^U+RrQhK6ZqsAJF}O+^ziwagbx@f*k+='
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
