# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/maksimdrachov/pycyphal-demo/public_regulated_data_types/uavcan/time/7168.Synchronization.1.0.dsdl
#
# Generated at:  2022-10-01 12:13:28.448545 UTC
# Is deprecated: no
# Fixed port ID: 7168
# Full name:     uavcan.time.Synchronization
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Synchronization_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    MAX_PUBLICATION_PERIOD:              int = 1
    PUBLISHER_TIMEOUT_PERIOD_MULTIPLIER: int = 3

    def __init__(self,
                 previous_transmission_timestamp_microsecond: None | int | _np_.uint64 = None) -> None:
        """
        uavcan.time.Synchronization.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param previous_transmission_timestamp_microsecond: truncated uint56 previous_transmission_timestamp_microsecond
        """
        self._previous_transmission_timestamp_microsecond: int

        self.previous_transmission_timestamp_microsecond = previous_transmission_timestamp_microsecond if previous_transmission_timestamp_microsecond is not None else 0  # type: ignore

    @property
    def previous_transmission_timestamp_microsecond(self) -> int:
        """
        truncated uint56 previous_transmission_timestamp_microsecond
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._previous_transmission_timestamp_microsecond

    @previous_transmission_timestamp_microsecond.setter
    def previous_transmission_timestamp_microsecond(self, x: int | _np_.uint64) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 72057594037927935:
            self._previous_transmission_timestamp_microsecond = x
        else:
            raise ValueError(f'previous_transmission_timestamp_microsecond: value {x} is not in [0, 72057594037927935]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_unsigned(self.previous_transmission_timestamp_microsecond, 56)
        _ser_.pad_to_alignment(8)
        assert 56 <= (_ser_.current_bit_length - _base_offset_) <= 56, \
            'Bad serialization of uavcan.time.Synchronization.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> Synchronization_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "previous_transmission_timestamp_microsecond"
        _f0_ = _des_.fetch_aligned_unsigned(56)
        self = Synchronization_1_0(
            previous_transmission_timestamp_microsecond=_f0_)
        _des_.pad_to_alignment(8)
        assert 56 <= (_des_.consumed_bit_length - _base_offset_) <= 56, \
            'Bad deserialization of uavcan.time.Synchronization.1.0'
        assert isinstance(self, Synchronization_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'previous_transmission_timestamp_microsecond=%s' % self.previous_transmission_timestamp_microsecond,
        ])
        return f'uavcan.time.Synchronization.1.0({_o_0_})'

    _FIXED_PORT_ID_ = 7168
    _EXTENT_BYTES_ = 7

    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8=q@;80{^XA`;Xhk5k9whI82iwa1fwvifr7M6rW@pM%vUD7r6KltM=K4d!z;egP_QjxIL1qa!Kiwz(Dguiv|$T0%8BfqJKtb'
        'W_QV@UgrS4Urr*qv$Heb_s#55e|_cO|M_T#{uUoh=8=k$zOQ&Lf<$~33=`h>Lzzyb5(TdoZygtT85U*EPv#R|eOGnAsa{l_#jAc6'
        'q;UUdWiSnctY3(f_mAgU80RtrJB5&0wYcn0d9Ltdyt8=y3-kHA>d~b~JAbdfsTObgK~dylSQcDW&%y2nkLstY#j6hlPol;X&yRv4'
        '@C$Tr)9^_yQc;L0JaOeTQ(~O)Xpj|r%=7lL-t>o}@DrYmi@1992^bFpRrsllcoo09c<;~}!eRZpaPI(b;fnrN9aW2WeN_Zm6y%X>'
        '=-YA_zq+_K$@x^sQu#$5WGWR3qv2!ZU{E^oQxWD;@la+_wRpvkWLPc!dlGYokFZ(HGgiR2!=w9O44$4IGZ?3WG296hGbW3IM{JbK'
        'l%5RBJm*=#Cgm^@D(3kv6B%=+QGIVPf=7j_jloCzI9QT785)UP739V)gG*vWSM7S3yB_i;l{t7F2bm``&h%U?7|UHf*9bGnR2(D;'
        '8*=s)&t<=Y7`?r?d{<@|!J<w{d?kL*eEP|w%kfX+_aE(GsN)a*K~a70VE>tac>3An!QK6n!P6)H;r*k*(|c9?;UfA{&-~mw#1(}E'
        'N;Uyx$cQDFNLc?qOCgIq2X|x%US+aiA$X3VC`>HcBWJNlILpf{6WO?5Enf4dK~e&=es00X&mlAvjTZDSACa9Pv5Sj)i#JAj5aLw@'
        '_aB(gaDQ>>W`)aCLs;c6H-zFN8-!m_0FEEtKk`oo2lt<zo|rKB2d9ru28WLa_aR~*KHK}j&dw4^nM#5wSIzSC6w)$hY9@*>W`$${'
        '%lOPj$)w&Q%Us2rD~L)~cp5Uf2su3{fMq$v2l8CZxIu8vLq4I&r8buY2(Ov6D0DG6oI@h|-UG19&w(ZhU{IvNSY!mTqA}p|0jGeV'
        '1M2hxM4@N949MBWt{LQQ9MpNndhAC3V*_K=-O~m%7y!-Az1n`xN16h>A)kllWLe;tjx&gT#BO!j9d@(1)MrFXFhh&U>cFgW+vX+n'
        'h+07^OSp=0CAK2POonFyKiAm@)1rvMVTlvfnZ#>oKjY^`FBW6Gmx0Fh2KV{^*!YG)Zv64$(ybbzd~wB5a(_72<pH6};&<X}@vq`L'
        '@$XB}*N8*tflxfEzFoZSkHk5T{E5s9Uqscx&ijjZd?m{~<ZvtD{v-hXT)d9|5;3e6ZyZ8lIzPm#-+^9Vx()^56vQ6r^Hv(1DUn7%'
        'qF7Gh`(z%@Cm=Gth^G=tmFBXa^KqG=15M$8(XZ)32EvPh12X^a=5Ie)u4w(6{TqGccvYa<U-9EWfs2?3tT<CZef2HyEWNt3^8^4d'
        '^RwPeL<UJ}iFqccph4N3Vyy9O0i#%58UT{$t0ifvxE4|}3s?i7WFZ*x>T0n(SCEWl4!KPceZxS3MXAY%PI^}dNURjr0h$JkzbBMQ'
        'X2c!>2zp0c$)qGxM;t<Wf|J}$WOxSN;21P@cmGN6vr=6}&K~sH=R6<tgo}b$@vzUJm*66d`{d@BXFLaCfbaxX2U=c&^uz#Mh9v~Z'
        'Pc;Rjq)eEIfS}E&RwicPxh0A;bq&+&0jY{WWY$m6k+5i@YiF+uYpb5gc7eo-u{Kw35pDS<lul6&u|zoqlCrDo0YMzRy6er5`b7MC'
        'xh`?RS&_34qpupq8U_Ozm*-nQo0f&EfSRWO9&n1DLTsSRz#+vmkXk5*L55WkDzz?*5!y^70!5)zCLGll(?o$WxXLvCY5AsBdIJb2'
        'sSVsgwX8*!W?h{}m)a$35~3RvWN$x%QZT6tv`v*TF%woqbxfiXI<u@`TVk($nrqp_{>0N<gXcld8ea|7@`e>KCrBI5A{1p40>Tk$'
        '8xeroiFmFM7ErL}*p30iED;bX6l)AXpj4Ui$b<Z0I1-6oNQyD^mBtSktK(H*-m%@H2b}(nb$EZ=-=#h-U?1PO!On&gg*=7PYS$}P'
        ')<8wrX%M@8c0$-X7ipQYAcVRTgam4kS;42+V8gWN{b*^?v_?;r6a1#I<c31=hIdFu=tpDdmS>QmJ&lbSJfo3OPnHIA3`4}nc@Xi4'
        'f{zZ=Y5~!cGo|ySiyZ{Z%m<#qbkH#rI+2kW8NFm3(dQ5ys1e{65Ju)*w@(qd2NZ*3QMhgAU}#3{GhoSGI3aAoDIK@QMNEMnlcOg='
        '^yg9)D7YT11a&t@Plc6X0wol#5wtmw#*y3oKpmjxwBtQA3eO}`P8j9+aBxpgg0h#(BtdsIt^mzZ*MQej3U5KEWeU3-991{(gr+TI'
        'p*2m)9QKM3aUh?_LX<6V1{NcNp-4nAzwH4q2$yD1AQD4;%C~7u&{vU_TxU*BscJf2>Sl!yQRrmA2nA(|TSkj)gv~3}Y0XZd&d@EO'
        'Jy#+pq!Ky>j8Trb81Cyt&VmWnTU2xC+sD`_U_H}R`AZ3TN@+?I7?cS!c!N+d^Av%87X=f138A#2iVo$}D#>#D1$YM3+Rlpv8O(4E'
        '!K;x>MHbZE-&GAZ+Y&C_Wg+H-C^4jJiU~n6qNaI6Q$l@b(}Xvexb>{=TWLc_rHVb%n#*k_bkpy-O+U@Hsr_DU_}L)SVh$T{qX#e1'
        'qI!g-A~=JEPO%s&^W<zfD%(RwW>9j3nj}Gpct}By1)u>~in|?&O_lPR-Epf!Z|#{hbSb5|n^A?KF{J|J7?3c?Y;+U}6o5A^lR_Zb'
        'R|}MFdUQLmt;JMG7PD6L-@&A&O1%lh>j|+6@lsrjOsZ_-%<gv9=hG4ljd<;hG1@%i;_q7jc1_hriKq6I7@W_b3V=@$pYjBx4kw1O'
        'f;1~&Xcd;0ONe9vA_HOTnN9(>+-t+*HS(-s>=Y0v96T({njrC+%juMw9|%=21vMjKu}g#rV_S`NXH3NrF49@ZrZ7?z`s{(kN>=yf'
        'n5noZChGR}>mY7r+J_}&dRNnz`MA&igr`DyUYGEKo8y&wRi1@$5Jd=KKrAdEJcDW*^>7eG0e#2FVk-w|)Z20tb_{6G(QybKtT4q)'
        ';a=S6vgtpa=E|0Tr@hl%HZ9S?1<Ye>aiJw+1WcpuEfHtPGg2(CerOl!9<rht)l5d(-E>me7xD86WKcK3!*+#+t;pJD*h4GSOz2^#'
        '=>crc?DnM2cC%i`ag5r^zN;|w1SNsusEZR(ZbYd@fJ_uGBN<}v3>!St$0TwrLYz3*R)SH*uz%34foU66b1tHv@*>F<#U$f;VeW1M'
        'OM#qaraPf@x<>-aktmdV*uYt_4{5Kk?nKBlPZ0L?C3|w{)XWPuHGyR_=seGn#QJ1lm+7uHV4puZJ~p_dlS~ELfO|@7f8BDOdGMf0'
        'mgBftp1!GLZ^?tRXOU^^h{yz%p28Mo$YGBvs5^r~LCqSTE##17Mt|3@!?qVCY8vDMv7^il!Y<(07ZJOChuzpS*PBz~bLVV$f)66h'
        'zI<|e;13?`-@SkQ9LIfq<Hepc7r|jvW}!Z@thcAl#@K{b0Xf7-V0?@tC_|27QS(>#@-@u+X0GKq4z&4>vn<#=;s{?r^v-u#s>a<F'
        'SFx)>NkT}8Y%0%a*T=JUTZvldRCCwar8`7vHtY3lPltFw;~W{TJWTZ_0WDP2VQ1rn_eME(bM^tKWK)qBB^73*jY?^w2(aqA>jL9W'
        '?m(KxCH0Kv7(%T*gjlm`J^PHB#zX+LHJa;wVJQ>F&6D#JYxJ&(Zl{$9*SW4S^0oQ@G6-~x5d_`GEQ((^i9W1RSa$~~sPhTzM>fAb'
        '!j*E^V>+t41&%PyfKFD;&e`VKWrGVbO#(W7gfK&2k7bo4QnzVTzi%>-!Q!h;kjF5i)17re#A479n%PXSPg%oT_<rqL*Ll_*hkq7t'
        'FnCLVI^DhX<N6o9Xo9j9qVWq8{d{?bi$}DytRA*aBX+Idt@XTcK0D7}yS7Jc1~QDWQ>tGgLB1l~AB7U?PzYUQ1H=x<w=LniGHC7A'
        'GT&6+?&i8|H*GIho2fo*sQ|Z^r9MCRVdI=QnxS#y{MCX<g$oaHIr`{!HEXOwqbduy8*VTSRuAkWdM&*k!)_t_4V~-JiGq0@h8ypd'
        '8nvN_DOxaGIX>Axx$mDI-h+R8Z0#TT@C8N&_T;x)&+nRV`}h8MdVFFm>je7PH=9X&H#Zn2QOIbIpqo!)!qKno<JXzkRBH8sj>QL_'
        '8tF`#ql2d0>NhmYlA?z{#(^j+9Xi_a^_f&%G?$+4Sl+CWAMj6~&Nl~5bwdMm#gh{71>2>$eLrj8gf&KJ9fTa;@u#I6tH|wPq3?f>'
        'cik@Qm&35$gO*UNhuU%(szX;!aKm^(==NJZfvqU!eFPqn)(fe*Y(_GAJ)*z%@GNMOwBE>@wlgTUQn)tOkhABG%`kDqPeuD+{ay1^'
        'xkSBKWo*q@xw*H&#0E)m?5ughHMYuNJJ!7TGk4rEOO&+(oXcz7U6Lm|%(=V;Nm_Q+H8lGnzQ0!Pfyc{qG|N!bCF{t%bhh1uEs|Rh'
        'N_?QbuwO3~NarqbU6y(m<*^nT{KLJIg4l`z?RJ*3_9?s3Wz^z0nZb*#fYNUWd~<@dG0`xtZN24(>8RVM2f6ROOvh~jy{T-Su8PbR'
        'Uh{^ibL+f5opd{}w%y1_%h=g&2=pIT9clRt+uV*5KRg#`g@Vq_S7zMS5-!QsrcQ|`dPm;rtf2_IbH^o8m!zY!At&%`J1O05?m?1{'
        'P=oZ=N)rk6(v@U%3uDp}IU6iJ;!c}--K7VYCnYgaV_1zY&<?=9NBO~7R~lBkX?*E6)BT$P<;O7DCe2|V0-x4u)HQaqySK$+iuGbE'
        'F4zAWYMo6CyBj^gWaGH=1?TLp8NV(Y7uI9<?}fMhJH-DXMZ0yrMCSjW2wLi;_Ac-W8TJxZxA1k@>I=PAO<g)kU%z#6PMubEF8F)F'
        'VWO(VukCNpnx7x~iWke@tHqB#6UAfte$4A%+bw?R%Sp9hn~bP=I+TeBtHqTAo=Q{Kp3*V9%$uK4zUGIqNTMqC7e77>q6i?g@=zS%'
        '-6v&|1o?dVZruB4)p_*EztnJX*`H_&)uYSh5Y`ER#Ghuuhu|DPypBK5ERz8J_wcuO_=Znr)su3FKTYcY53{x3GVv+^00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
