# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/maksimdrachov/pycyphal-demo/public_regulated_data_types/uavcan/node/Version.1.0.dsdl
#
# Generated at:  2022-10-01 11:53:16.157620 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.node.Version
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Version_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 major: None | int | _np_.uint8 = None,
                 minor: None | int | _np_.uint8 = None) -> None:
        """
        uavcan.node.Version.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param major: saturated uint8 major
        :param minor: saturated uint8 minor
        """
        self._major: int
        self._minor: int

        self.major = major if major is not None else 0  # type: ignore

        self.minor = minor if minor is not None else 0  # type: ignore

    @property
    def major(self) -> int:
        """
        saturated uint8 major
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._major

    @major.setter
    def major(self, x: int | _np_.uint8) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 255:
            self._major = x
        else:
            raise ValueError(f'major: value {x} is not in [0, 255]')

    @property
    def minor(self) -> int:
        """
        saturated uint8 minor
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._minor

    @minor.setter
    def minor(self, x: int | _np_.uint8) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 255:
            self._minor = x
        else:
            raise ValueError(f'minor: value {x} is not in [0, 255]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_u8(max(min(self.major, 255), 0))
        _ser_.add_aligned_u8(max(min(self.minor, 255), 0))
        _ser_.pad_to_alignment(8)
        assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
            'Bad serialization of uavcan.node.Version.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> Version_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "major"
        _f0_ = _des_.fetch_aligned_u8()
        # Temporary _f1_ holds the value of "minor"
        _f1_ = _des_.fetch_aligned_u8()
        self = Version_1_0(
            major=_f0_,
            minor=_f1_)
        _des_.pad_to_alignment(8)
        assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
            'Bad deserialization of uavcan.node.Version.1.0'
        assert isinstance(self, Version_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'major=%s' % self.major,
            'minor=%s' % self.minor,
        ])
        return f'uavcan.node.Version.1.0({_o_0_})'

    _EXTENT_BYTES_ = 2

    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8EGjr-0{?YXTWb_C6kf5HwcaYN1r=;m(E8x0ufAzf)YV$7^+6~xlbmj%nPf;Z>#iW^gJL0|(D>{8GoI|Ft=0|<liPQ4&i8$1'
        'K2QDnJ=GdMak(A{FLXgYIK{O3$Vv?b<+iG=R{>Hyy%Ai)L*wAppoX-YZhlFh(n_4BhE=$~(6An7rZ84O@fw_0)}+{`z41`C;_PI3'
        'H+7D6THn%_6i-qXf>UJ^z^5&YcSI(8r&64Lq(F=P4Cbg{fzgoDItpGpRjHtQInhnyRo8%cVghu*{awyUTB<-bm~N1%)5hSO`9LeI'
        'D#^vTv_1)xVZ|!$J<nTMQR{1Znc^b#ff>P^I2h=AQ_AT$U9or8r8q@}<terjuFj9{l?!rdJi5?n%Zu`|T%LfGL6E#6uQnybg#&!i'
        'axfx4!-za5Z^&y6Rv@5uz*zv1cH$Yjt@<EnZC#*Bq_udCdfPY-xS@g84D*Y#`J+{t;)!(>yuY4Tcae`{w~_EoB-5h>D)!#1N;t-)'
        '?cuy0@Ift^z9pctDPF3ZQY%g!bQ_(o-xmhaGb4jw`Pm{V&X3(t+%4`DS+f)}feTbJk6Ae|A&b~k9MX=w5_j$sFR=(f>4=AlnV>is'
        '+l#ndvquaIIK4-#(E~E%o1h$INMbSfN&=~!4VGI?x){kZjpu{~PmB$OTf@N_qJjs#O+Kg~Nyr!$xSZToWCcr&C0(DGZC`3kIs7|M'
        '@zetqo(<<4I31fU9;dcWksKAo53154pUBB`<QJ`+OM6jc(g7W@XW1FbrNV}gtMTkQ6GEBpp+oYqe7HASjptXfP*lkLH)K39iii^A'
        'mOOxbdLYKxwMJ{^28Ylyw8wM<=|@`Ww14^%e**O=Eo}RyMDkFL+*>$c{XCe>{e_mv=s61gnwjB$Vhuas%`m9knnVL%%D0_)$?z?4'
        'L*zrW({2tg`?4vEKdtKRspbR#00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
