# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/maksimdrachov/pycyphal-demo/public_regulated_data_types/uavcan/primitive/scalar/Bit.1.0.dsdl
#
# Generated at:  2022-10-01 11:53:15.985452 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.primitive.scalar.Bit
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Bit_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value: None | bool = None) -> None:
        """
        uavcan.primitive.scalar.Bit.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value: saturated bool value
        """
        self._value: bool

        self.value = value if value is not None else False

    @property
    def value(self) -> bool:
        """
        saturated bool value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: bool) -> None:
        self._value = bool(x)  # Cast to bool implements saturation

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_unaligned_bit(self.value)
        _ser_.pad_to_alignment(8)
        assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8, \
            'Bad serialization of uavcan.primitive.scalar.Bit.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> Bit_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _f0_ = _des_.fetch_unaligned_bit()
        self = Bit_1_0(
            value=_f0_)
        _des_.pad_to_alignment(8)
        assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8, \
            'Bad deserialization of uavcan.primitive.scalar.Bit.1.0'
        assert isinstance(self, Bit_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % self.value,
        ])
        return f'uavcan.primitive.scalar.Bit.1.0({_o_0_})'

    _EXTENT_BYTES_ = 1

    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8D=Ii+0{?YWO-~d-5Zw(dAovji@!~=BVDR9mf4~DIURKtPs5jH8o^I)mJ=2~3*zA~)$Uzg5PBhu_=8v_S1r{;PWxA%iUcGv+'
        '=G*e`KTEx{CqHzZ2*Ok>NUy=@ufUD0SZy0;gN_pOox|u;9g~;uJ1235Pfzd|ck_U?&`|zCf=LZ+<-Bfm)Du~S8VvYqPe;saY$AQo'
        'wnf#;s~^wLGaUAZy&rgjd4oZWUh@=Xz)yG+q038{2d}j>VnJk`35dXAVRuvcB{^!iXRVRY{yWVE<2o`U+oPz69D&vlB5SOWsJ8R{'
        '@dZFBtM(~(P*OBV?>oN3yv;&{R)7~*fld=wgFKjkNz{3n30q_CVd9XtuFTDNHy865)sET>#70QxWergZJk596XFZjIIqM_S0!Mk1'
        '1)F>=DPbgYK)v#6c^S<y-x`y5({cGaquKh;Nwg0nNFX;G_!4v@Jk-igD0W@lIR)mKkc}lbUE)U9%*&%>O8bSlRJ}6ynmSw&bY<>0'
        '=G)|W^|E?V6$daDS+<yhK>WOHW3gnSYl)}ok$OyOa6^z!E(}}9Mi=Atc#i(&EIy?0+_=2Nti!x>6G-S9ZfPE3azOLZIz-yPw@!M9'
        ')-UW|VYSk<RO(f}HwGbed-UHWwO_KMWN6s#dX^C8F8{>cVgFa)wE1ohgu}JOY1~G)bSwv$mcwe<E)uy^uQNGy(4PGqqr?MGy!s2i'
        '$ifAu0{{R'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
