# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/maksimdrachov/pycyphal-demo/public_regulated_data_types/uavcan/file/409.Write.1.1.dsdl
#
# Generated at:  2022-10-01 11:53:16.624724 UTC
# Is deprecated: no
# Fixed port ID: 409
# Full name:     uavcan.file.Write
# Version:       1.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.file
import uavcan.primitive


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Write_1_1:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     offset: None | int | _np_.uint64 = None,
                     path:   None | uavcan.file.Path_2_0 = None,
                     data:   None | uavcan.primitive.Unstructured_1_0 = None) -> None:
            """
            uavcan.file.Write.Request.1.1
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param offset: truncated uint40 offset
            :param path:   uavcan.file.Path.2.0 path
            :param data:   uavcan.primitive.Unstructured.1.0 data
            """
            self._offset: int
            self._path:   uavcan.file.Path_2_0
            self._data:   uavcan.primitive.Unstructured_1_0

            self.offset = offset if offset is not None else 0  # type: ignore

            if path is None:
                self.path = uavcan.file.Path_2_0()
            elif isinstance(path, uavcan.file.Path_2_0):
                self.path = path
            else:
                raise ValueError(f'path: expected uavcan.file.Path_2_0 '
                                 f'got {type(path).__name__}')

            if data is None:
                self.data = uavcan.primitive.Unstructured_1_0()
            elif isinstance(data, uavcan.primitive.Unstructured_1_0):
                self.data = data
            else:
                raise ValueError(f'data: expected uavcan.primitive.Unstructured_1_0 '
                                 f'got {type(data).__name__}')

        @property
        def offset(self) -> int:
            """
            truncated uint40 offset
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._offset

        @offset.setter
        def offset(self, x: int | _np_.uint64) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 1099511627775:
                self._offset = x
            else:
                raise ValueError(f'offset: value {x} is not in [0, 1099511627775]')

        @property
        def path(self) -> uavcan.file.Path_2_0:
            """
            uavcan.file.Path.2.0 path
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._path

        @path.setter
        def path(self, x: uavcan.file.Path_2_0) -> None:
            if isinstance(x, uavcan.file.Path_2_0):
                self._path = x
            else:
                raise ValueError(f'path: expected uavcan.file.Path_2_0 got {type(x).__name__}')

        @property
        def data(self) -> uavcan.primitive.Unstructured_1_0:
            """
            uavcan.primitive.Unstructured.1.0 data
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._data

        @data.setter
        def data(self, x: uavcan.primitive.Unstructured_1_0) -> None:
            if isinstance(x, uavcan.primitive.Unstructured_1_0):
                self._data = x
            else:
                raise ValueError(f'data: expected uavcan.primitive.Unstructured_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Issue110_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_unsigned(self.offset, 40)
            _ser_.pad_to_alignment(8)
            self.path._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.data._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 64 <= (_ser_.current_bit_length - _base_offset_) <= 4152, \
                'Bad serialization of uavcan.file.Write.Request.1.1'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Issue110_) -> Write_1_1.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "offset"
            _f0_ = _des_.fetch_aligned_unsigned(40)
            # Temporary _f1_ holds the value of "path"
            _des_.pad_to_alignment(8)
            _f1_ = uavcan.file.Path_2_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f2_ holds the value of "data"
            _des_.pad_to_alignment(8)
            _f2_ = uavcan.primitive.Unstructured_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Write_1_1.Request(
                offset=_f0_,
                path=_f1_,
                data=_f2_)
            _des_.pad_to_alignment(8)
            assert 64 <= (_des_.consumed_bit_length - _base_offset_) <= 4152, \
                'Bad deserialization of uavcan.file.Write.Request.1.1'
            assert isinstance(self, Write_1_1.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'offset=%s' % self.offset,
                'path=%s' % self.path,
                'data=%s' % self.data,
            ])
            return f'uavcan.file.Write.Request.1.1({_o_0_})'

        _FIXED_PORT_ID_ = 409
        _EXTENT_BYTES_ = 600

        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8EGjr-0{`t?O>i4Wb_V7bq9hxZESX-f?XfIN&@K(rUU^ObZKycw<);0#j4ZElND3SRP4>ux0Wvd?2v<49O(iKPnbc0=*%T{>'
            'lv0(-@)jML8;?AyDwQf8dE`+?R4&Qu`N0nX@J}Qa??MubgYNh9z1MGg$o@2MS^CZUv#Icp_iC+CcFJbH=uq3xP2+2Q-lX|rsamO3'
            '9mA!8clM8{X;kpCe7jMj!MDM+Uj^R;IZr7XmPPG=rM$DByLP?g)@|A=A{Q;af+k+9>vv1Km0vK>_Lnx=%HN`YUZ;*5c$wl|YCA^N'
            ';)c{;#@F8lBu&zP6Z|UhP8W68wT=0@OP%1)(CQG#ZK=SMKQ*XX?%)_JmUUMzx*Xgv^_tCtH149r`7bQTShQ&Q=ax$ssofjY>EgWM'
            '7ENj`x-1~vcu9BMVx?N90ejKAIGY&aYWYua4)_$0=&yrYf%kmTadoS#+vRRU_v`a)%u}ih3l7DsNX2rs6nLoshc85q**H_<t1&Oz'
            'ozYnx4X`up86uDr&l!6T^VHGvUK)}y+twR__rfoA9L15(LMS)*Xm7}8i`1kQYPnGg*-NqIS4f7v%3dQW9vHjatj~L=FdH?!WVnrh'
            '{I7Q|4zIYt7i6IJ>ye&RoHw1oyOJR7qy|B|J3j~BnLjk#2=C|kF-Gc%#cD0^v|&b^MrFQg8kpGgKr2<ugNw!XiyF0cw`zBnc8M8S'
            'K<sDUg-@zhNq4C=P?U$uC2eZ)(nR@ZZ`Msyw;O$uO7X64)@ktTAV)I3GtYh=r{Ocydf}FCEz(=GMqOhVq_2t<eF>9_3b(^S_GMx#'
            '%wNT@0+QkvC<ZOnQ+Z9+O&vu^nv14<2dkAX)pRSo$!^x?DFP|sI+P)mVYEw-F`VU=vDl<qSYTJ!Rs49~%V0`)3AfYEOS5-TKMWTY'
            'RZo5X)7cxhZruLGtx%tR>AjpR4&tz>!-4eNe3@Hergby1jyk6nY`w%su|hJR#@9IS3D@5Xc<qHiD|>+%gByk7XFt99v)eN<8di^8'
            'u&+Jwop;}D8>8O&u5G6{--vcHZuBcQ$!un^zhr+=$IYNjF$`WI<>0>e3>NwlEf;H5+btU9;HLLn(W%z$5-svOwHPMSQ~5X3n8)&&'
            '#Z7i8ynnyNMNYqkd)F6ulVY4_EBaTCQ7L1zta=we*BYfpjp^o_Wh~tQ@9FwHmU7Xii@3(<zO%=nwi4|RxRG$bsLg%k-^owrdGZ67'
            'Z$#&dOm`5H&2MaUde<n?;6A%j_@8ttbrUydTGqI^{MZeRThW{bj#V^{UZYkCceS!+SlSo2Kb^{Jw;9!{mf6s-%#E_<P&CX-STh{W'
            '#kqy5eGm6M%`tU{X_wx*#LYT}wa5*JV>ukWrrC4><Ja73sAX5Hu2wcM!)U6Z<@lIcErlhbRTs2-%qTJLqD&VI+_AO!MySWbq4u@>'
            '*e#05!NQ8{B5LYrIhtS0YnSqQbcfMv7WWbB<IWs@#v2eTlBXc2n=Y%?7a1BxM-{!Hl^DNWdF)|ib^hc-UwB{K#a!|_)pFbjwJ_=u'
            'EnoX!Ow-=fZbYf8RSguf7I}<%lvzxZu9=4Q6(5UojV{dy3Pniw3{=!RS<MeO*vS@J4M!5gotfDBK+6G}W}ig2#iu=+)U&gCxr}c5'
            'HYc3@V|<R+qUnHS>b;xF(7j~PlkMgB$=2Qy^7u4Pe!M70kGXW`G1q0|dVKZX;QRk0NTu1wU31y?(`RtRH>06H;TwDRj+^b>z5g`6'
            'DsuaS_GZjQs-25mvcnP~{w{{!F($z$QamQN$B0NIpD591fnTdVb3`VJPcpIIslGX)A__9r*2fY2e0rc9IYq{NaweL~a9?MK%8}FL'
            'j8C5Fv5TWP_Ux`Y<Sco{C)wDCPoCRTnmmgcC+GS+;S7$S-<Ljlj-2z!^O3BC^Jlp3g?;Oi^W=G-TpWl2XL0U@1KA=M$VH!wCz(bp'
            'FCJK*yg<f%^1Y#$Py**)I+R`VBKe+AzTcBCoJD&tAKD&yiG1HDuk4B!rBLS8C-OmFCa?HJYv-1ue(i}Zl2?i5lS`2uZ8!Yf`|C&I'
            'kGw`M`Q&oqvuhoAmfkorALMm%*(X=_Tp85RP#R^g9;t8g2D##sToPxzX4j6~2f0deKKa4E<3tUV|KYLVAlJwbd@|8l+skM(*S)@P'
            '9-CkCLo(r${DJa-TB!5Zv0@@`lDtnQJ9UtYD&g&8_e$O(lRkOpz!^bJ)ceti;3IF7cYJcazhWlP_GD5u@17VI@*{HHCqF(^&QKe5'
            '-#byP<X!S(pG@^u*Cem6_fH%Ld5=u_<by-!4lSVmhff7Jd7pgXlaGei;dS&e#cT27r-qMwNIvq(Po5~hXa#Nj!BdTad`y1glj**i'
            '<*PrFj86BC7kbBM!kO7<j&<hdcFvN5PnP=USu9aYWSZSF%Y&uJl22A5IWEz}S^RMqb#f>*g_<)cTR?q=8YsKkFS~-$4~EIF4VPa<'
            'jfaDDHulz8L#_3ldYk*#+d$1n-MZTc*WE<ztwg_dc>Qg(@EC1CCLJ5W-%k&0r`2s~e1|18&5c1eeK>o$UG1SeZW6Tg!K_Xlz$!xE'
            'hG8<jKie~hwvDj3d6-V`?xAo*9uO*b0<-DCe%P`2LHLm?m`itiTRIVM7!-F1wKVtH?D7fA$K)0x>-W4e&@%#xor8b8{#W<yAECw&'
            ';K5O&SbHKA7(@&N9zHpijU&f`;l*%Z{V<3&PXrML9)p5M`@^;U)No-+x}m|=0CcVYf9Nn{F+h0CG1gi1Ll&e2NJ)@VAeA8*$Ow>;'
            'pd~{_Az8=@kd+{-kZ~9nU|fQ61zIZ6KodZdKvPH#asuQe$SGtJCIy(3U{WDdFeSj01XBu`hG_w&C74#o49o~HBf*S9W?@!<SqWwp'
            'Qh<U01qliYnS(h2<|LR?2m>YnlYl9t1~ma{64Vs31WN)eNwB0~YL^9AmS9=I+%^ShO3+j=xxN6t1ipgVT@heKf)xeR`#^vP5<E~a'
            'zpDbQO0cS6f*%U-P=bdFW_V42H3`-fO!2w^>k_OhnBxrrHYC_kFv*VucqG9i1+%;<z@`M73fY1!0k$OAQZU8a0&GjLtzeEH3-DNi'
            '#|o}OOMn*UQ{jb>5+Nl+O68@H5g~&~R(UaGMaasKRe3p#i!d(3xXKGc6G4+fQ+Y|`M99gIQ+ZKLiZCg|q{_=;N`xsHrc_=S(;`gE'
            'Fs<^^m=R${h8dL?$E*mmGR&&HJPINdWGJY-Jmy50lVMKf)xktyGBB0bM@@v93^kS4&yomBGAyZB#jq^GvJA^A)-g0iXv)x3v68_T'
            '!I!~Tv6f*)gcTW9RIFxrAi@I~9;jH)uqwi;467<uG&~gHp$rdItZ7&iVNHfL6{{N7MOc?%UB$YF4G}hE*if;u;gJZBWO$@vZNsJr'
            'EfF?l*i^B$VM~N98MaicZrB!KTZU~F>l+@6@K}b&D&C2H!X9T?8M5CcawEeJwMXQ}36LAvC=VlY;~2<|ERKfRJyLQ*+v~vO7|0E+'
            'cO8Cb$qlVTNd4ZB8$9OAXgSxrzQ5Px2G2<@se}=^v4h;`t(XzHaZqw2+GY5`X?8?zJOQ~8J(Wh}#z~MHogJ~8+~A|rz2k*wd^)c2'
            'esUwCB~mz(==G8t$^35QMnY|*Vwubka)V1W!`Z#bjb7Qk$&JDCyOSHc>kKD1_NO<P+&GwSKe@3Su0<2Ivxg@)!eiwQj+JmVcDJ+C'
            'W2u#p8;K=;Qk>xjHR;3J%MG>1&wb-i_aZm?tWF)k>K^1qpY54L+2-f6vH6|kMxTem5qa1_ZuI$K$Kr>dorbQu$&FS*ZggreWEqa!'
            'Th~EoD<L<MW6%_L**x+f`wxg)3Axen+)Q^n=LfKRmf~JV`MdgG-G~2`bT5QMksG_BSbHKA2PQXm#j<haSoT3~?22gfL=X)mH+IFf'
            '{nT)A`k)PMYcRT2FS>9e;nYU+>7nZ-H(D{d(M@eYMuAKw;WmVr+fX2z;S2{SH$sv_dYbeGEa5+alN{1udV|v%F~c#UH-1;?jfmT5'
            'iTkHF;#XGW=*7M0ofVxmzX|UARXUYo|KYH|z0dycCiB>@bIfP|!2Xea%L4Wr?^M_OY!|v;U&+7S{RS5M=lkr6_t6bYt9Qw0rK)Mt'
            'Qu2n=e8Z*AgvMW4n$T?ho;Gh-y4}!>ioQsPy{z-E?W_M}{}#WG^PQt<M(?1EXqpjCGooomG|kD-H2ko0MAM9Dn*Gx>or)RJG>4&S'
            'c<x3t&4{M?uF^EU#{n6BBG5h#$l!0V^3daer+F5T{BOt6S-|KlVAxqeE8Tk>pmvS}B;IEwJ`JG!G$6;`U>DiHv)rBk;>QBNtq(aC'
            'VE^QuyFU4T+yLus{M&UB&}3H%-w3HxIH?&{*to-{l`4J;n>>x(Znrhj9HyJ5Rx|Yy4LgvOs+LPF*Wu>{VMh|)ZArVzfnJSlMWZH-'
            'dWA%NQm*n=99K2n4QHdyQ<_twB?I-j#8{WDX!>e?Z0t)$E$tq{<Q+$%{v{I;3e!LkNpBIG)+ldFV>YxBM;kUziMz~1O-DF9-oOP>'
            '>E*k+RSH{}bfDBN*Wh||EJTj#+$#pE@$O_Mb*b6NYatx2buY}E!~2R^rBFN(EAPO^;l!9|8&cJxnyEXO45LCP#zKVMdBLwZkB;#*'
            '?PQvxPui&Pkua(#X|z&v8xwJlntKL1<ZZ=tv#Uc5UPk#Jb8X#n7HHTnXTh)xhtYD9?M`^ru=ff-8tRH~qT65;o@>{`wpCFR9qQE0'
            'aJixq2&3d0?X`}A-1{_XaC4L=lk9GolH;vak^`$8E8|zvKZgBF^uLWKSs8MjwlZz$9piWY9`D6SV;X0svi%x6#-rPton~iPHfo@D'
            'k>%KL4|t2;`EL|x-_mzB@sp<(=@P#`16V)jT`ZR4etLG1QN4`ccD6;+4%wJS8`hYnAPi|ta}!grelBeMmFaH$6(){PZVi~^s`>u|'
            'zC$8|L{I<#'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     error: None | uavcan.file.Error_1_0 = None) -> None:
            """
            uavcan.file.Write.Response.1.1
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param error: uavcan.file.Error.1.0 error
            """
            self._error: uavcan.file.Error_1_0

            if error is None:
                self.error = uavcan.file.Error_1_0()
            elif isinstance(error, uavcan.file.Error_1_0):
                self.error = error
            else:
                raise ValueError(f'error: expected uavcan.file.Error_1_0 '
                                 f'got {type(error).__name__}')

        @property
        def error(self) -> uavcan.file.Error_1_0:
            """
            uavcan.file.Error.1.0 error
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._error

        @error.setter
        def error(self, x: uavcan.file.Error_1_0) -> None:
            if isinstance(x, uavcan.file.Error_1_0):
                self._error = x
            else:
                raise ValueError(f'error: expected uavcan.file.Error_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Issue110_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.error._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
                'Bad serialization of uavcan.file.Write.Response.1.1'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Issue110_) -> Write_1_1.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f3_ holds the value of "error"
            _des_.pad_to_alignment(8)
            _f3_ = uavcan.file.Error_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Write_1_1.Response(
                error=_f3_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
                'Bad deserialization of uavcan.file.Write.Response.1.1'
            assert isinstance(self, Write_1_1.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'error=%s' % self.error,
            ])
            return f'uavcan.file.Write.Response.1.1({_o_0_})'

        _FIXED_PORT_ID_ = 409
        _EXTENT_BYTES_ = 48

        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8EGjr-0{@j(TW=dh6pl;NIB63SLPG^YU4&Fx(QYoK4e(M0$EhqQyT*xIAykcKcPBohu6I|vvnH;D)IJooVx(5;^noXC61Tzw'
            'LPDYfAs%?3MFR1QIOBC3Cv^mN<al;2-}&ZTzO&a4-X9wqYJcSMsO2S|Z<2(?ocjD4b$n(LH*7><!Ua=ue3|*YfkSVj6)|;Bow}jk'
            'S108m!h?Xt3WntPx`<O(q%qsQWtarCfe_E9wCU2o+~kOTIYunA%91Dy5?suaCW{ju1{!JPQfGWmm2>6X2kM5BhY1xT=1wYDqOPd@'
            'D0eq0IlRJ|@9ppyBOVo$2u%(~vPl?|Q@yl`aU9}hj=%&O9@2(k>I!Z<+Sz_=Kf6(^y~CSmce)lNydE&G6bM#l@osM%CJq<GXF*+n'
            'Do-LSmnMQVLJwKJBxfqyK>C<jz_m5Kgq|3>sj5moOA<i?kH%gv(5=+Ls|+`(pCW^U#0y;|hZN3E%X|S{jAulb1RR5xJEIfjNq7Zb'
            'h0__r0lTcggjtMh2kXV{`?9SlW{D2VuG{9TRNx%-x6xryj&8=()w2n%uXM(^E^~8AUm|hP*!+KS8LwGo%f4)pVzp{l+q7U2-s~8G'
            '3v&4UxpQaF4S+am*&AfVu35`{&~gg{AmvN;zO-_KP#Rw<6pHKXWVvXSiv4IEm_IuJ+>sJOm8!+UhFyIJ(d31a$;{IRmIZ4>SiMHf'
            's5kqbu0A6S3~EGFfFXbiBMNyS5<`SI>+zVmB8*#V51WPgK`vLaE-kH=mI?l^6*Zm3qFF~ey4DP>3I<P%AQT2B8~2ROFh(lO5Hzkc'
            'k?l%a2~vN8#vs9(SShU*$%bu{)urmiVm~J@EDqviyS72>6|!DgD)dKteGn(<q+G96Dt2|Fe+Hc0fn##IM+b@1%CuF(o`K_V9v0vt'
            '6yR-GgLmOFFrW~^Rk#LCxCuAl4txk7!Tl6f$YWT}F2$5kx8(%c<Xg-mQ5XxtJ!Q!$l7wmOGNOY(bdo4JqJMnuC^=fewy;&vv-eQb'
            'a<izmH55dw_wfe3n(&5)RS#hkpQD!Bih%lOJk|)6d?895pSvVx_0-qqcT^cqAIiiSB~05@a-uEB=Day)Y86sKOW-sCnjoi`1wzYk'
            'le<ja#_XE4SfX=WgPCL4TvA^c;U?yDPbwK<#NxJQnOZ3wAI+ZF7P%csMPRY_S;-@Bak1KdUT0lBl~0i{QqtHDBxyCA5buo4*U$&p'
            'GPHHOO#{14PcL<WW5<Gr^63ioJRa1a*aW}oRV(#<8n^bY!r~ouvOIY=aj>688G<V3QwQ(a;DK&8IG|g4Frr%yMgWhM^ZMA(-2|Hv'
            'syq$az1K>eb^>EtVOdwi%uF2$AETkaVJ3l3Z^LI6d=6ingfHPM_!_=}2k<R?C!cw3?u|}|pU1y$<ly^T?ezWue$4p(1V4AL^;>uJ'
            '3;dx;!y_z|$N2pdcmCC-1BbCaPwKV|Gyj7O{L^C@Z_Ty@rj1&=o|7|J1ldbXOaNsOf3lZ@ok}&ZQcsn0y8N<w?MwZkJc>P57gNwT'
            'v~o0yEGDedZxg@wM9aWv?Sgu)N`pG9vWN-3U!GjeqBw^Kda?3%+b()!!DGCi_FFf!Z3nWXv-nA$MSax#7YVZ?k`)R700'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.file.Write.1.1()'


    _FIXED_PORT_ID_ = 409
    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8EGjr-0{`t?U2Gdyb|#0z8CvlVZO4uh$H}bYjp<mX<-b_YCcDx)a%5Z|Nh`~-7Ttm#kypB-P$WA;+ER+33X0vzD2q%t+^x1P'
        'Py<B^72O9v^g&OB9`#bx=#x;OfFAW|pf5sS+H+=x<WM9fQI_OpS8;qr-h0k>zI*POd#QWOGb8`%zaIpg|BCPCrc+ib9Zy)?H1xFb'
        'r9PVG@kBB^naf&6o|lTR-Q(sXBgu!SbG-Cz>HOEFuS&7vp@hl*sKBj!B2WDyP(1W0PaBh{lB$(d5=JJ&O-JNj-Yg{Z1#=x(IFZpO'
        '(bSs-{ZUfS#K#Qe@W4c@_>gO*RE#7Zanmxg83Iy2_g;TnVnG)CMd@qgnb7lj(-<w}xmEf@L~Sy)id3l>zHRVys>-7+k<#<JJELam'
        'Ig=)7JVJ@%_cN9;p5duGnLHooX6>Y2ON<)%M4D&D^P<EEJgK9*CbKDY*E_|NgJmF6i{HXApdp&k&r3t4;_C@3uV+%aneqcYDU6CE'
        'MI}2nW^we2oJeJprDC9j-EX;u#c6TSdv&B3^?P(sM*wkD9A^>>kk7<P^ix%@c&drVOjDmO72o(=$6oBY>rm;T-t|Gj(|nR=%0Z!d'
        '$nUX;I4j;~0h*XNKU)|r9zbv8^rVrWF0ubD9`mM`7^4Mgs2y|l<iu#&Diz-^Gp)J?N$1zUFBK2|*vPwl@8MgIX)%<@=1N7a8HhDK'
        'Ihsuy=-A`HC$s2>JO<l9j+=TuYx+YwDGUrCakqHlRyLE=^E}f~l%`9PCeKi4qWqEmLOQLR({++c;*p*%@X|M>7>n4}sOb0H@DtQ}'
        'V@S`8^C6z&d7~MnFA|gb6gm|Ze(H3JpOvv3|4ka15)04^6oWOjs8UQ8(mIN=Ac+QS3!{}!<@Aj6ko6ZvIT8`L4h94wV!|gVCUKOI'
        'G1%ms6JQra2fl4DM$jb`!WFkuXx1)jx3j3Idf;B~V9!v`@W7CxFMd`$U0xjIVRDOz)I5BVA;;5tx{QuG2gXc2Nxc{$k=x#D94|`O'
        'Zj>nY9HQoCWZIx-ByqR5|FhvfkB#`!Ga>$@7`k%(dIgLZkNdWr#OSoUlM!f6To;dpCH_qOX#qEb6vt^$grrJOiia`Kr+6xn%bNLw'
        'kt+2Uk0z{a!A$Z5J*f%Dkwuk$q>WJwpF!M=r<~{aTU_MeCEUC2<3oz`JT$3)VHuMtoUO<{!uPr9<aAEx>5C~0-4Z_2g;5M;+^)xQ'
        'jnRB{k3((6-5+oxA-kweHsV*}opEx0DNh^G@r2MVq-4^AZMla*>4~^7@;|{qpdUA9p3(>|-qxcLie^n?-=s$DHJ(Z0u9nh_jCOzc'
        'c2`^*7F^3_($gA-xslQ=j=&Vcnqg^q92?7;k8#h_th8<k?aZY!1Zx?YaRPSwV%T|JGx-?KU(075Ei;?VYbgUgj8M~BjQY~qq!S`q'
        'c1(LLjHDnFDL!W4j;)POJ9;!7Zk~^~4RLf129}G9thuGdczisror%ZM9L`?LkPS~CcV_23K7bgJ<bs%<&WmheTp%zSn$)MYq@c%@'
        '=I+d_KqnvC!sp@<`jX;QixCLV;H;B8b^fC^O}nV|xUS1(4HU|Z(;Rizv*;#WOB<OlsL%B^noPS?I8u6SprT&&YP>mM)mw<_^pt_C'
        'BOZD~<dWzWeePqyYBs4OgL*23X6iO4938-OJm(IVSfo(9sWjb78l7yXy_2o7CB*SGE`Pj8xyM|vdd&GSZhEgiZv6cBKp-f7>>G<#'
        'PM^jzzUOv*P8+*_$BowR-n#cHMfi>OX7oj%;)_^$hh>uYGvxflIY~B?y}odzkA;|QGsS%`(QCD4jD?wEvxuj6pl*z*$bz+1^sxuu'
        'zt&KW9bj!XJLrx@$kw5za_lvB&}N5gaIqKrj%=vI4za^Fi+VO}c63u|b_6}nj@4Ph5$r#{C4F|39kbc%uB?pX2TAwDmUY>2_PWhZ'
        'HspY#IQB+MSnLElX|wjSr;*E>E$g#4Si8;MYRU;EaQxJ^aM_#eEt|bv<1ZXVywlspW2e~LHhX77z9@w<@4l1`cAC9oGp*uVV*S0B'
        'Mr7|Y&1Pp@9Bm{1Wc|GzvB$p0&e-g1*`{wD$V=bfF&peXcGhO^Z@Mz5p`kR&p4(B|?ECC}o5jlW^w#YBj@w}8Sj=W0Y<Zrjf$|r2'
        'g$Fy&KCoFwb#2cgX3W377kAAryTCeZ7H`Q9sD(P0c9j#m$l^BZtj0mijfBg)Zk1hPoi@ADvPV!8^{(y-KX#d2vDvlyi0MG=&T`aT'
        '-!m@kD!XR054Ytr)JEMKd&-qvXCK<Et2VkiDZXy*IS+P&b=mBrZTk)pQ2z(7gg3j%KC;=z&ExPI+UTNK{N$DKV?SUY+w6xg<zGZW'
        'j32$yIj~RI4{g?67qhhbedXTn+WwK+{yt}9&>a)iv4`tN*@(@i>c@pAkt@s0`ekMsOR*`N&AD<UF^i-4aTj%BDAk3UeJDGE`T{jj'
        'cD`PA4yB(qlV4~qKaU#E8tE);uCstzi|h54x30H@n$P{ZtF7xUqxMQ!e{K8vtBCLdF(4B3K=Aj|mT}hnNbT#85SqXs8r&XUY(qRW'
        'N06WeTSM(?0Tn3_FmwjDhTXSqY@|i-&>h^^!pII;K&oT}27`_5h+VOR^j%Z%FzB~7wI|kaQe+TvL9#jPvk5c1WEN*uZ+WhvWhCSo'
        '2YYwz&u`g2QuQdn)179q@KP*r5*`tF_VQeocAN`N&!Yp2+hMf4Cya379w~UfHD0T)j2F7ZPYqTYuv`28#|}N_5rh}Su^=WLju4O_'
        'AVWZbK!imgB0)rkwJ<~!7KNw;Q5m8NYln6T+GS{0U`=HjXcA~LXbOu#OoEsUF@<$Prv#lcbSkV1x+Lh5p-W-i&@Dl?4BZOrgFXrR'
        'Wav}aAPh<{D8rz_MqosO5gA4l_7EOQ@KA<_3KJkC5Hbjb<sc_PPKKPqreI2fDH)~|bnT1;GcwF5=-XKdW@VUF(7Cn*whXp{-kp<R'
        'PKG%J-TPF6r!qWM(7*E%%*!yZpo5=D@Jxnh3VL`!f(02C6m;>T1dB2(D(K@S36^A7QqalIC3r5wa|OM;EWxr2%L-e86$w^kSW(c$'
        's}iiru&SVsUr6vmh8GI1!kPqY=ud?LArOK<7y>GVLL>wcbh1jp5Dh^z3{jQBp*;lcVQ5z=AhZx@VbD|xiC73?VTh>|6rCaH3`3_%'
        'VbK+Wt}t||6d2th=ng}-N}<sgg1#{HsT3T8As7t9pi1E}5`vL1jHnbI4@2-U3=dU`4iN$o2BA`X<U)`OLr$gmnF_&F7^YN=VwefR'
        'Oc-WVjANJ$!E6|2Rg7e?Ltux&Rxy@gE(CL7m{T#D;b{n-hT*A-@eK1Jm=D9eiV+RZLhvjM&s2<QSO~#F7#38FYFG@xVi*=xjB8j5'
        '!BQBORE%tR9)jm#c&=h>!*U4LLa-c$Wffx^Rzk26h7}c~8&*TG8irLB;~QRt;6)f-sQ4t><?L}(7!ds~B{w2;slA`v*n{Lo)b+!D'
        'a$^^g8&T|ayt|{x4Q;avlU+z|XtnF`JDc3lstKvzo8$(~`79#GYS;JoI=MkUiIpQ^Ke@3kxltQ2`^k+~lN;_XLl>vf{p7|=Bsbhs'
        'X+OEK7s-w4j_6NrP;Yl_|A^b)?ZtR~a>Gqa1aPFRSDV}@k8hORD5o|8o=l`ka)Tshozcyc8?~~VCpQ|)Z=BrNSf_b%V{3YilN+t+'
        ')+aY+oVA!m?dbNC8_u<ImB*a38XMzG)gY~vlN)6ux+#v(MNM$Kc(JB<bnoj;b+hC~9cot#sGB4=>ahE^g-!Re9{l>`MxBL`9kQ@4'
        'xlw0F?1~+_J9SL?lN)R0<VH0Hoh-wSTk~Cnu9cG;<!jIYnVjA6N!DKwua%P<Rm-zMzj3;N-82+8yUO3t{`?l~&jo8KY%963A&Z5V'
        'V$pJPV?!=WJI-Yb$&C#eE$<1VhRKZ$d9A)OUX(tlP+MutZmpJ`vyo70WA@dtt4(gKdC3ibY6Bt)L?Y$fhUDco6o^JB!$HXnC&?kd'
        '%Jc?I;r|jPIpoIa4N7Zx8IJw*#_wu+!_951g|?pF@V>GVcE7mierH7&fALjm;z=+N5dUI{Z=MLdU;L#g#l)|~uf<=9Iq@6u*Tn<A'
        '@3Wooe|;r>+5ZhJ@pn(eh2qCO8Li-x(URG8nkUQOa2lP?bE`w6uPk+Frv6wPH8Q$6tr?U0IB)i4oqw#n`d9H!-uH37b7`9W@1X3b'
        'Y4+1J`)Qi}G|k?mY3Q<ZKTWfrrrCO$rW!H(X`1b%X~=i`X`1~s&383TQ+pi{p&Nn9bwC7vgAF&m4tSM!0p)+~xPKS0e;3f~E?_NK'
        'dmW%wuLESNv*O(baJmhMi4Vjn@z3Jo#4=qA{I<~KT0s0w@z}M_n_dB|%lOB46EG_-jC>^p0?wdjWSqhsCZEjWJEzD~+i<0<iDn5s'
        'oz`+`J;|L4B*|<h&og<8?hBlXBvfrlJ4Zy%xma#*n!B|^+&U@es1(OJP0u@{ZsjS>%JHOu`Xtfj!*Yku#oO8*2%ga%BTcF};?^(e'
        'a9N}cBvGy{V)7iPvNY*wElF&h;wfI08Mo*N(W3$`$VyK=(lbe?gh`c3A(J;qkGDC@QJt*fL^Y~nmgae$o{nn{9nyO2c+R4_Vwt2P'
        'UKUHO<41HnPP{@Xo8ekox6m2JB=2Z*82bH!e?321#+SV6X<}b4qe4B-tX!w@$y|QA!>dvA*g%6+R!mR(D%9Xh*Z*yKQ_omq+^Lr{'
        'W@HRY@Ko8`)#+uO+ADN5<eOiIAJCm%-Yhs}tK1?w+$yA<<#I#7nI&md*4mxq=C?_Wi=(`pq`zQFj7qDNFRWt1z`y1CG2-vte{I|;'
        '42V_B%2cG+^-uf~pG8-r8%MgL^&0E?-N#!*#Zhs>EueNvTok`;@e!Z+PZX#;(i8uM?}}=IPto&Pg2iLSlZlj9PtQyUuBY(F`m$)+'
        'HVe~e%?i_uNKFdU^rH(Fk2!_EBL2c(j^k)>rNN+6Z|raaqbirpSlpwpde+)}wS3-cRQJ!-DwW;bun5pmzhbXxX3e_7Kfd~Q>uUN`'
        '>V4H*+%_x^RwFJAum)wpf}I;z7^{IebibeV4?O5k^bQSGN}l=A!XIA0e)W0_hzI%yh7-33?)QJ%h})GGkRo>mn$ilkLg`S?ty{hK'
        '?j=6$?Z4C8h?aEuY71}&?;zBjq261=14BPWwBnEM#Cf~}&!s$Vpq!2pJ$1?3|1x;wI7P3Vjng^JtaWv-O6%BMx!lU+?(~1&bN9}t'
        '32g885}g~p&eglKby5*H+Igugms{s-jEZdGUYgg<aXcb?b<*l+w6a)-Z{NAwn;0G#NZjoi`mDE+lds%p#mNKrhZ6(06ZZytZZ$^h'
        'YQ;$ul=tor4h{?rH;#a-RXBG8orvRyn~4voxk}9?YCfUnCN-Z?bBmgvPy^Kb0W}Y(;ne8V<futg^T*UYrsn6=d`-<a)ciR%8+-&i'
        '>})5E5;2!*YTgYwhbEo#dQJ7a$_c#rX<1h^%$JH`(Z(AqZCl*k@O=5Ef1rt-!N%I+!GjC3F}aDqMYMWCJ{}VqNqD=oV|?3OCL|Qc'
        'kN*=Pg514>4nG7mKj&tG8=P}bgH4y?Xx$-Js(wVMo<R{5RlVA|b@lBg-lmD;9&A>QKi}^U6aP*w{Wog<gPP}+2!`JTH+Jt6?=wbW'
        'H2!}L91V~DR{#J'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
