# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/maksimdrachov/pycyphal-demo/public_regulated_data_types/uavcan/internet/udp/8174.OutgoingPacket.0.1.dsdl
#
# Generated at:  2022-10-01 11:53:16.540512 UTC
# Is deprecated: yes
# Fixed port ID: 8174
# Full name:     uavcan.internet.udp.OutgoingPacket
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import warnings as _warnings_


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class OutgoingPacket_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    NAT_ENTRY_MIN_TTL: int = 86400

    def __init__(self,
                 session_id:          None | int | _np_.uint16 = None,
                 destination_port:    None | int | _np_.uint16 = None,
                 destination_address: None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None,
                 use_masquerading:    None | bool = None,
                 use_dtls:            None | bool = None,
                 payload:             None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None) -> None:
        """
        uavcan.internet.udp.OutgoingPacket.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param session_id:          saturated uint16 session_id
        :param destination_port:    saturated uint16 destination_port
        :param destination_address: saturated uint8[<=45] destination_address
        :param use_masquerading:    saturated bool use_masquerading
        :param use_dtls:            saturated bool use_dtls
        :param payload:             saturated uint8[<=260] payload
        """
        _warnings_.warn('Data type uavcan.internet.udp.OutgoingPacket.0.1 is deprecated', DeprecationWarning)

        self._session_id:          int
        self._destination_port:    int
        self._destination_address: _NDArray_[_np_.uint8]
        self._use_masquerading:    bool
        self._use_dtls:            bool
        self._payload:             _NDArray_[_np_.uint8]

        self.session_id = session_id if session_id is not None else 0  # type: ignore

        self.destination_port = destination_port if destination_port is not None else 0  # type: ignore

        if destination_address is None:
            self.destination_address = _np_.array([], _np_.uint8)
        else:
            destination_address = destination_address.encode() if isinstance(destination_address, str) else destination_address  # Implicit string encoding
            if isinstance(destination_address, (bytes, bytearray)) and len(destination_address) <= 45:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._destination_address = _np_.frombuffer(destination_address, _np_.uint8)  # type: ignore
            elif isinstance(destination_address, _np_.ndarray) and destination_address.dtype == _np_.uint8 and destination_address.ndim == 1 and destination_address.size <= 45:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._destination_address = destination_address
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                destination_address = _np_.array(destination_address, _np_.uint8).flatten()
                if not destination_address.size <= 45:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'destination_address: invalid array length: not {destination_address.size} <= 45')
                self._destination_address = destination_address
            assert isinstance(self._destination_address, _np_.ndarray)
            assert self._destination_address.dtype == _np_.uint8  # type: ignore
            assert self._destination_address.ndim == 1
            assert len(self._destination_address) <= 45

        self.use_masquerading = use_masquerading if use_masquerading is not None else False

        self.use_dtls = use_dtls if use_dtls is not None else False

        if payload is None:
            self.payload = _np_.array([], _np_.uint8)
        else:
            payload = payload.encode() if isinstance(payload, str) else payload  # Implicit string encoding
            if isinstance(payload, (bytes, bytearray)) and len(payload) <= 260:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._payload = _np_.frombuffer(payload, _np_.uint8)  # type: ignore
            elif isinstance(payload, _np_.ndarray) and payload.dtype == _np_.uint8 and payload.ndim == 1 and payload.size <= 260:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._payload = payload
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                payload = _np_.array(payload, _np_.uint8).flatten()
                if not payload.size <= 260:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'payload: invalid array length: not {payload.size} <= 260')
                self._payload = payload
            assert isinstance(self._payload, _np_.ndarray)
            assert self._payload.dtype == _np_.uint8  # type: ignore
            assert self._payload.ndim == 1
            assert len(self._payload) <= 260

    @property
    def session_id(self) -> int:
        """
        saturated uint16 session_id
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._session_id

    @session_id.setter
    def session_id(self, x: int | _np_.uint16) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 65535:
            self._session_id = x
        else:
            raise ValueError(f'session_id: value {x} is not in [0, 65535]')

    @property
    def destination_port(self) -> int:
        """
        saturated uint16 destination_port
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._destination_port

    @destination_port.setter
    def destination_port(self, x: int | _np_.uint16) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 65535:
            self._destination_port = x
        else:
            raise ValueError(f'destination_port: value {x} is not in [0, 65535]')

    @property
    def destination_address(self) -> _NDArray_[_np_.uint8]:
        """
        saturated uint8[<=45] destination_address
        DSDL does not support strings natively yet. To interpret this array as a string,
        use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
        .destination_address.tobytes().decode()
        When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._destination_address

    @destination_address.setter
    def destination_address(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
        x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
        if isinstance(x, (bytes, bytearray)) and len(x) <= 45:
            # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
            # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
            self._destination_address = _np_.frombuffer(x, _np_.uint8)  # type: ignore
        elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 45:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._destination_address = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.uint8).flatten()
            if not x.size <= 45:  # Length cannot be checked before casting and flattening
                raise ValueError(f'destination_address: invalid array length: not {x.size} <= 45')
            self._destination_address = x
        assert isinstance(self._destination_address, _np_.ndarray)
        assert self._destination_address.dtype == _np_.uint8  # type: ignore
        assert self._destination_address.ndim == 1
        assert len(self._destination_address) <= 45

    @property
    def use_masquerading(self) -> bool:
        """
        saturated bool use_masquerading
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._use_masquerading

    @use_masquerading.setter
    def use_masquerading(self, x: bool) -> None:
        self._use_masquerading = bool(x)  # Cast to bool implements saturation

    @property
    def use_dtls(self) -> bool:
        """
        saturated bool use_dtls
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._use_dtls

    @use_dtls.setter
    def use_dtls(self, x: bool) -> None:
        self._use_dtls = bool(x)  # Cast to bool implements saturation

    @property
    def payload(self) -> _NDArray_[_np_.uint8]:
        """
        saturated uint8[<=260] payload
        DSDL does not support strings natively yet. To interpret this array as a string,
        use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
        .payload.tobytes().decode()
        When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._payload

    @payload.setter
    def payload(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
        x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
        if isinstance(x, (bytes, bytearray)) and len(x) <= 260:
            # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
            # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
            self._payload = _np_.frombuffer(x, _np_.uint8)  # type: ignore
        elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 260:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._payload = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.uint8).flatten()
            if not x.size <= 260:  # Length cannot be checked before casting and flattening
                raise ValueError(f'payload: invalid array length: not {x.size} <= 260')
            self._payload = x
        assert isinstance(self._payload, _np_.ndarray)
        assert self._payload.dtype == _np_.uint8  # type: ignore
        assert self._payload.ndim == 1
        assert len(self._payload) <= 260

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_u16(max(min(self.session_id, 65535), 0))
        _ser_.add_aligned_u16(max(min(self.destination_port, 65535), 0))
        # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
        assert len(self.destination_address) <= 45, 'self.destination_address: saturated uint8[<=45]'
        _ser_.add_aligned_u8(len(self.destination_address))
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.destination_address)
        _ser_.add_unaligned_bit(self.use_masquerading)
        _ser_.add_unaligned_bit(self.use_dtls)
        _ser_.skip_bits(6)
        # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
        assert len(self.payload) <= 260, 'self.payload: saturated uint8[<=260]'
        _ser_.add_aligned_u16(len(self.payload))
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.payload)
        _ser_.pad_to_alignment(8)
        assert 64 <= (_ser_.current_bit_length - _base_offset_) <= 2504, \
            'Bad serialization of uavcan.internet.udp.OutgoingPacket.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> OutgoingPacket_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "session_id"
        _f0_ = _des_.fetch_aligned_u16()
        # Temporary _f1_ holds the value of "destination_port"
        _f1_ = _des_.fetch_aligned_u16()
        # Temporary _f2_ holds the value of "destination_address"
        # Length field byte-aligned: True; all elements byte-aligned: True.
        _len0_ = _des_.fetch_aligned_u8()
        assert _len0_ >= 0
        if _len0_ > 45:
            raise _des_.FormatError(f'Variable array length prefix {_len0_} > 45')
        _f2_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len0_)
        assert len(_f2_) <= 45, 'saturated uint8[<=45]'
        # Temporary _f3_ holds the value of "use_masquerading"
        _f3_ = _des_.fetch_unaligned_bit()
        # Temporary _f4_ holds the value of "use_dtls"
        _f4_ = _des_.fetch_unaligned_bit()
        # Temporary _f5_ holds the value of ""
        _des_.skip_bits(6)
        # Temporary _f6_ holds the value of "payload"
        # Length field byte-aligned: True; all elements byte-aligned: True.
        _len1_ = _des_.fetch_aligned_u16()
        assert _len1_ >= 0
        if _len1_ > 260:
            raise _des_.FormatError(f'Variable array length prefix {_len1_} > 260')
        _f6_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len1_)
        assert len(_f6_) <= 260, 'saturated uint8[<=260]'
        self = OutgoingPacket_0_1(
            session_id=_f0_,
            destination_port=_f1_,
            destination_address=_f2_,
            use_masquerading=_f3_,
            use_dtls=_f4_,
            payload=_f6_)
        _des_.pad_to_alignment(8)
        assert 64 <= (_des_.consumed_bit_length - _base_offset_) <= 2504, \
            'Bad deserialization of uavcan.internet.udp.OutgoingPacket.0.1'
        assert isinstance(self, OutgoingPacket_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'session_id=%s' % self.session_id,
            'destination_port=%s' % self.destination_port,
            'destination_address=%s' % repr(bytes(self.destination_address))[1:],
            'use_masquerading=%s' % self.use_masquerading,
            'use_dtls=%s' % self.use_dtls,
            'payload=%s' % repr(bytes(self.payload))[1:],
        ])
        return f'uavcan.internet.udp.OutgoingPacket.0.1({_o_0_})'

    _FIXED_PORT_ID_ = 8174
    _EXTENT_BYTES_ = 600

    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8EGjr-0{`tjTZ|mXaXb6gQj|`jC7m9Y#<WZ=?c-|s5>K?P@I=xf(=6&hkph#zS<cS%-V8Y}&&(cg1q7f!641s1*~A-wpZtgc'
        'e)1;>1LVQH0Ol+F<R?EF7%&(ZK?vk0RoyeQGkbRwU#HmC3E<xDOm}s4y}GKax^=1imt~_M{u{pI4~)>TTb+;xmS$U@Yh9bSI=bih'
        'UT8&pJluMO+m?f0jnf04kAF7a`Qz~)kDJ44$8udBjLpJu>!(rB*Q0*G^GzxpS91`=_P(~PYi`SOBObUsYV{4j^+`Wk@+^00QPVH*'
        'XgsWUmU$3bo=XsGpT*yQHf9B;{OS0|<KdQ$7Da*8?MFNu{}92igL~R)Jgoe{;<hnCsL?UBNb5v|<$B%yfM#ngV~cHP+|XKbxp5p3'
        'U*bW2c3V1KE9%(XU5d;xn?c~Z7DgS%Gx*qiefa8P0*Jb`4&ytZS2UwP8J`*tzt#yO%{8>Z$O5|D@0yKaBjh2?zhfEWVYy>?`uOY#'
        'rBFC+TA|vbNvZfH<dGVAs^+R%fFJ@b7^usd-REj|phhNF@sS%M5)sl_b#Zjna#b%dctHKST%{?~S4WF<Q*;S<=zDI+8yBreKCwMr'
        'v+aR;f%}oFdq|3vsHL99H@&{AM~J2B^{{0Yvt=uY`l6R*a5u6L0u2+HT11V{99ew-_@e52LDX>jP8XR?5UHa;ABBami|6+_4?H#0'
        'dYr)Z1WqA$jdV_i$3y%UsiwBfRi|%9mXFhlQ4JA9!>~f4LEj2Z1RP!D+-;4K(yvHfnzQDc@wd0xjQNiFP4ivJh#7-ZPmQM8A$-T?'
        'j^SH~znXa=CZfuT<iQT#Tt`NOKpTvQuYIQBQ+#qlFn@ub=7nr)huhpi5=x=Xpjl7R96pDV=WDtZ4aRKO@a0&PI)WQ(_WK4?NCai?'
        'a;IyD<Kd13(}^%5($Vzq@$mVNtw`egDgKNx9hN$tKOU;<0SO0A*Rw4hl?u4yAsvWtpZGk`A}`2V72UK@WzD0*R}Oowu0`BkvnfrQ'
        'S_a%DV}R{nJlVHxRDo43s~sU#<3AfWS$!0C&EJiQ@q5_owNskA#7}XbN7i~MUFbO43X&E(oDvVsGYKp~KgV)Wsp$(g15+8+$O`mr'
        'jruc%+7?Ev82>Gazf57p5i7^fD(N#;V&xI5%HKu$Udz2>6;>Uwdfe~1Rqt30@nVg%KR&_VTh?sHo@0#>dtSb)(^y;AZO68-=SS>?'
        '99(>g&t80JAGVdfFk&<D7$f%57q(_EvY8QkdDTex2A^+xr2gzB_VS2*O|~uL`{$|eE05flZDU^>u~*l`0pH@g*B%QNdxgC^VzUXQ'
        '5tr8=yFYu4&5qa`>*9nh@co-l1ed+e-WajBa`eKt2=D7p43E9Z-WsvDABr!w!Zz<b)fnvS?ClX#Q`!>N-*{?>>>Z|#*mem=eHi{U'
        '`Zu4+c<dW&`-r`pjG5sBQR!RHYz+2I_U?%7_(INL4;5Qu+xMR7*z8+u$A~qPdB!~3`OL>)@3H2HefyE;i9N9WcQynMwv&B(#O5Zv'
        'eHURiv;5t)VdJvzu(=UyJr*6X7xsDo+2fRA#CEaPh_xqD(3Enp`^m=4kC>-HIv#tUwMT5vV^acqV!yrXW0uD&Pl-Go@|;PrV!PR%'
        '5!<&~KIRZ+JCTw7c?|ND$<rmzi98>2l97(Tm+c#|51xoNY!CH4u$n%3zU8@=my@iNWMxE9hHzv1M{GVXEp3vQ4-<^DJju&SUQ)7h'
        'l9iH-jL7lW2kZcwAF+c^OcR8F{l7b*%WA2~%1l;bvhtFZmRME<euy3WkR2Sc@2xL4`w-?l$<Fr^EV7c5m7A>8WMw8RF;ns)DTFwD'
        'mwj)<K6)xTv4aHTccx`1D?wTL$x6=`%Z{Lv#PZN88A2ZQF?{DMK8DM*>mXZPf`WpLE<;_xb|aWku;~?;Rj}_>P!;Tc4Vnr<xDIUv'
        'hqwXr3OmGZ!XbqnW4GX#!WP+WSX9_qb_dQX>>Rtx9>6(;nd~0M3Cw5r*~+Nj<rtJ`7@2j!S4{mkCTOUWv$(-QL!B`G$_EYPA{91+'
        'h7AcC1Z|&r(4c;iA>4qVLCy2ww>D@{CxPBqCTO5Jzbm-=n-Mf@5Js7xK}tb3Xn5K&H!f&+6wID3XvoXQ>Y!m`LWVuhC}?>4kYUFc'
        '1PzI_w57a=pyAO&hByA7f`+w2h8Lb;&>+{0hX)PQvh(X1G(78&VgIV2foLWDg*a$1e~ynSO1Q-86eV0{=(S>;KrsS_3QrR!P?Yc>'
        '6DMF~AVLL7Ihc*%wrpNXGmL<T;n>`9_NV1S;fUvGma9_kRrLb(_@Wv&P%oN1;39$MYXjTU3^g>pzHLylt>*<7wZPzp8hNe8NiX6u'
        'UDpk;9c4BXC_Gd(greEDcM)3?$T{k*@)gbTZTzuk|Nd6?U*qEh2IcHTV$spUAN6^li7Xy>DF<e#7ro#@DD!)S`$cV_YN6V9tuO3)'
        'Q1qhItJ4rU!FXPgc7d{qfk<-drslfbCd?@_+Ur?5&Lpsw2@uYdKzKfP5fhQn>jj>pYVJS{y?&r`nZV>S=SZY!1RN0wBW$0=snw9V'
        'Q5?m{a6)Fou;oDHD*1}evE!codsR=5cofd5ny!0+m{mN|k&~aQq0e;-F%_I{H4YDaQ?pfz((}X!HH-oa`v(bpk*m+8c>`|rb;)&y'
        'J6?c9b&Zq&-9EO%)~;yK?S}`|efx=2fkt4%RwMV5lDpJUbG*JQa=D?e>9MHbJ0gh{2qD7nKFSMsqd1N1E+Mgyv|(sb+8IU0Apn|-'
        'BD(xRB3_NAe6Vkqqxn8U%D&v$Qjbb03lBC_bvwf7J1t_GE(p`|f~D>1y8rFUa)kQt{%}ug_XqQ>-L2gZ>6YnFh^3e!fIaQ@?t^Wk'
        'JAZI~zqa>a8~>9Z^V%MMu)X&{`{04Sd-rY60!U{wC#8f4k-|zrNeI&brjg0O5;}wWqIJDxR6^7Ml3^lp6Zz2N0kUN$jkECa;Ufpv'
        '{YXi&AOC&W-X2dn%Z&`)YBMW$b9vd>nNP95KHT!L=h<9yb2)DFZKlXv_D^KWy&v*UR-q{6zHoE}6(LfoenahQ`USOVwRmd|B|Q|y'
        'CldoeqK6>FgOdxV(FUNj?VL*Y|8niI>om3z*<?$He{=?+9KivX0?koRQ!RzC3n#PzYSyP*?*~>iXsJg6&yS5Nm9kKc!jaP_J|%S^'
        'O%MA%b>l{>@rf_W1$wr&6bgj44WC~`2I3_1l`7`!@Qt-A2bMi538{aEf3j4>iBv<HK>;y8UsMW(+;sQE-}bLrKw!>8SusDHs)6{v'
        'eD{&LAV)Zo$(x^$k3ONydp0FLlTWYzLHzB91b?mMxv8;&*#))!8?@`SnJV8*m2alXH&f-Csq)QK`NpQo-`lWc`D2W_VJY)xh~E<>'
        '&o>a44N0YMAg;7)_0Z({mx#wRPq}}Ict1fh{!7Pi15@>1>Kxej*+=Uo^Toa#D?p(Lg)$VXP^i-eT@mVKcu;|Q73y``s4K!u8D^?5'
        'Q)ja<TZGv%%vRw+4QA_11+@rj8PqC<C#(t0A~eg;tg<$=i_k7ZyUONaz6kSWn6I)!aHt4}%5bR4j=`}a94o`IDqDobA}p3+vC7WE'
        '*&>`R!`Ui32j_}#t_<g@%mlLtW*N*X^T98IUk1O*R$!$FD`i-zvP*EO2$#xmsmd<H<sw`z!{sU)!KetMGK{M13S23|l`>qZva4{l'
        '2v^H+waTu+wIW<A!?h~A4%drty$si@>;~K@!i_TAsIr@Ivj{iKaI?y8!L1_PD#NWRyA8LCaJvk*tLzTkDZ-sH+^Mp=aJL9|%W${K'
        '?!mnx+$+PqD!UK&i*UaT_p9syJSf5gq%BfffkFui6)4o8u0Xv6btHI=HbrMjFjIjUq^<(9C77+iYz<Te)Dox_P;1aspjm=u1)4Qz'
        'E6^@My8`VR%quWog82%}*Wi!>he~j$0*7jFOo3x1I97pUHCR+&u>^}1SggTW1<sb>Yz5BN;G6>IN^q_M=W1XoV3xqFfLQ}y0lx%('
        '1^gPUD6mq3l?trX;F1EDN^q$HmuhfXfy*VhT!G6q7%4C+!KebG8eCD}N(ru1;7SdyDsZ&~S1WL}2G<n0R)T94xK@Mf3S2M2^$J|C'
        '!3_m&l;B1MZq(qW0yj%=vjR73a7%$(CAd|ATQ#_?!0i&;uE6aY+)?082_BT-P6h7N;I0C9OK`UWcWZD@fqNymSAlyqxUazd65OxA'
        '{Te(_(lU}645-`n%`%eBfO=IxJtOI`8BlLPK#lIWr0!-J$z~bJuYDOwGtb|zbU-~x>uv_r>lc<tiP;ROA2*<0tMFtqpnm*-`cVp1'
        'HUsKs6Hu>L=rReXWelCf)5SQLrbwDX>e;%8rmGZHV~g6l!8A1MnRpt*mW>LjF_gxbngZ+c+95TC(s5M18B+hYhSV~i#=!cKL+ZHP'
        'sutHvQHj+lrBFE9>v5g#c1Q}T;_C}UdBR1@wx=tq;=2_bDyuTRFjAL!(A6T#X*K9F0a-Z^$}$?dxPXdO98VN$X|B4zJ+F2L5f7<e'
        'CMn&bN+KM^2s}}k(WN>i2RjUW(XOF;jw5QPM9l%!<@j`wKubME#UO;!sUI9x4}7>=)C29=_d#1!ap7>5yUXByWFo@L7QdKQ9rgMF'
        'P9u=D9<mO|(N-*{?<A!Uq4ha`+?pe*r%I|J>W4j-ZpDZ)l@OV-1T}j#!%HU@PIr!;Jbmi-J8=AD=k)0l#GQ|jJAW8*q@nS{28enP'
        'F@UI9%T^~{;M~vGh^R=Nz@nx$aaIr`Qf*GPZ{m83NzoHBj?bxm*QTmE1k#WIu#Ja|?TN}bs!dTZnwD;=x+d#U2D!>PK_>@0#A5_p'
        'M-1!%Rj(K+G6<xnEh8?-QkP#u@_R1QOMTefGB<lrQJLd-D42XQo89ep7JiNjt+9D#`1Pdtgs)Hy7afYq-HcK{C8SET)B2M$!{>Tb'
        '_JdDDeE);^JH8)Q=0DiiZjb542~sCM+?Kh?rPCeATVjaA-!fk{=gg-0pJvPaFY_1X|Cqlze-#;ezC<6_=;N=bv}L%ZV^DD!T@PW5'
        'FArbn^sE(bhzmOC$`ttJJHwYcvTP4u*}UUxkvS$cj!fI?j)%`JdZD$lNKbz@ZVr|A5zR9p4-ogQj&>om90O-yddv9RAIRb|R0_u%'
        '58w3rUE9(-0blCdguvud8SGt^cikWflG|>^!&2Yy$HTYgcOTd{b?r^7-P+wEN{=JD5@uV+)I!8HpbI|`n`KMq<DZ~Z|MzS0-7gL@'
        'Lt7Fxje>hw<00!6Wqo3-TjK5(s_GM>kTXDWi{mktR4J;dCl*e&8jS^aAfbqRSSIzK>FCLQFEnRrkM>RqqOe~ijdURiNg%e&+oAMY'
        'nN<TPHJc$?T^*%EUQ8oL3>(=Yg)xb(Yp$9#wzHONSVA=9OsTaf-0Fv-WOM~Z6SWN0NRZEnE4&&$>Q*vCQC&v0b(WNKB(AnZ=2OnX'
        '3KKP>dMs}2Y^k62QPCw8k_8~Cx)a0?8{3_U%5F!p9TydoTokrZBch!!;o%^RxD&&Xm)fLD0bxCXgX3$KE!4Jg6y-JhiY^GE(z8$^'
        'kkE^xff}Uqv~Wny!@1Z{i4k2b>IdTT9zEbl#)d%3;7b7)43&4A1j5L>hUV(hy7#ocP51TKJiupMUJ;a)xTGeRDu#PBp^2Gl__&Jk'
        '0Efgm8u%!#5*?^U-?w9CCbA#}-LP;CCPhigbJOx<VR#eP3E)Y|X#$Ll6gG+ikCrJTxh^TWmMHKdPxovjPRQ+^m<XBeAY(zJi=OIr'
        'mo2X!HbPw2BEDoL@*m$`#2w%E1{3HRQXFhFsD5)n*Xd3r&$VTXo)sYIc$zqiC6}m_QXsh_N%IjyVs>ou<6+|&P(?7;sGw9$D4sYJ'
        'f{zZ5G~uSWxZL1KC=9gHP5UP(F$PBsbu3q|;|Z0K)1tH(RY{D20>LFRI>)uaAbsjP)2PbQ?k*Jo(`d+R%R?m<$~T8{icK_}hq&x0'
        '3I=nsR9y^^-1mgqncnmyl|~e2Cl^+QElJeHz@vGID(^&MNFsE*FKVmTC#M#MeJ4xJEIrU>gaRE+R9&NO=D{3^3JoR-$Z@=s261J0'
        'C~Z&REn8yj6jvfIQ7u6s2<R3fvM*u`3q{AuVxr?ulyq|W;xV#{F(H8}ZOTN&CY|4t=*MlXu4P-%K>8q|XD`Rc0uoKpoUXOh7v-%B'
        'ZX)R@19m@S|1>GTspv}jP(^(PDM5l*l*N*yMTrlCD~F#^NK&vK*%(o)@1fyBDZti9>8!1BG*^?fQe({<Op6ze<B);vWhGY_MJYJz'
        '@K{(s5;dtQX|3^`Fq0;682cl_7OfvBhgNUUnA9D|zF61mOMemN+DivQV=8nJy%s+{kAO-bN~i;xVVK4X;-G`c#q!)pR|kQNq-|^f'
        'r?8jyHsZSJS}1&^mumn<#$9l|i{#^@HyIJ#gz$!ROawAT*K@QkH_>P;aTg!iJJpl2xw;S^CJ_bEwp<UJ=sxb07znb&JZ<1`@hqhs'
        'bU5}Arv|vZl#Z4&PqIn(0x2^BQBfm}Ca7o8d5kVcmzg;Fu<PrRg*=?-p&(R-NKzpuo>AhpAbX^(Y)r*%b9vsb6+`Gekl|WlSfvDb'
        'v7<LZOZo_nv>h$bkw>6ty^<UblbaN$oCkG#>Y#6rjbpr$lOInCK*EJe=Fr03NGyIPexZ3$;30@h#pdD!#V)}!NetmjPHwW3qI;1}'
        ';KVM3Pz`ZPW_oUd&@G|=i`bI_%Y6st56s0zWdalDjH-=*l2tM5%k(1;IcbUO23sj|^lsPjBZ-(y7$*@#k6BF*nXE!gg859`Di{Nh'
        'mlRGeSezCzv4|w@hcE=5h<fExg>grG_h9Tmlda~dXNWR-dfFhYB{X8m%txMse8jmbx>aRVi~a^KW{E8oVdE+-m$8@NU8;U4eX0MI'
        '1m$G<$u@=wZ6<h=BJdSc>(lurVF0agjmXtQfHaLHn&eu5t4%PM5jH6TXf+2kN;cFb!9s!^)0XAp7%Q!oiE5IdCZof1({dwaUpKja'
        'VJe_cjzKkY-i*|qn0@iqh6s^_L7jLp+Ipws)OcY@2TJsfoD*q`$me(%ybyy@5$ng>Hv*;>8#1~{)5GOXfM{fAYRO|aY2YKErn^hJ'
        '<qJ1Kw3We*be=>YsU8!q^>G&ivPl4%E|PI0%U$;3P>nV@LQ<(!6qjb5E*8xR!)hxY%Qf<_F~u1NMbg5>8%faYqPdg;M!sF5D?4N7'
        'NKBf$VL#xLWjm{2GHAh`UD}5UFVIOs5oJyms8Hxu>_tt5s>m{NHjSJTo8*JE5TEzmfV5NwR|{z*XrptQ1C&I2$zo($?rIz}M9M6i'
        'iPne($n_dA9xjjf^T@W4miA(1da+lPM!I=wujXM(T_lBzR}+ebgw&A1vnDsUQrsDLl>$XEwlGFA@SNHYOpL`Eh9~xiQK_@rQxp(s'
        'b~y2Pl8r$0seIvUSUoXmvNTyQ!Qi$w5VkguibCJfI5Z|py}&*`Oi4)nsP9D@Sz%nR`i`Ro*5?>Xi8+Z|XvGAvy-5zY>gjqPDM<D-'
        '*3Ed2FQ)Irip5)7N#qtUL$UP`N|A1qgi|{uM9uuR&tw-Q*||XRCjv+xeG;vwre?}{T@|Z|rJ2H^DW{dE`?Q%uv*cUF(b7@58!%Dr'
        '$wAP>cEteV35kG4vN3!JiR1xAS_-pgV8sDZ5p5XR-P7D%y2)8(88u1gD1$&FIsPb?Bh*l1AWx7^4nj_Ey9z%G*W8Tty<iEWyFR8!'
        '(#*MOI{O%V&-iGvp)ZAij_K-XDM-%j2nSg*#i%K&=<v&}9ydb6Mz<K}e1_Bk5s^~f2u`86ijC5t!j&&xLZlf*wv)`esH@TfPa{6r'
        '?M;!y&LRw#9TL*=6)SN7#8#CROx6bSawSJ`9ijfNmjw}bO$VUaNu0>(N1Gr`c8pk;>l&Tfr2Qr7oQN!gwBB+7T4R?y1upmN&>KNX'
        '+8HC@^`_kcLe{r6JzXJ4vm`=OgiiG`T%E>AJqaTtBe6a$#Hj)wl^uCtAP@CuDgdL))op~4dSs-xs~oUY|71o+F4_$#PGm#o<f<W^'
        '9}QPx$B(j6rM9+XICaEa92TDFnr1I~0aC_Ew<i$^57%lpo_}(%mi$1nJn5lWKd`7LvJFSIWdPgF9{W#s@3K3&bB*jtb+MVMihXmj'
        'wWo8*CYp+7?;@E?myU^@YN=-uQ)^mF<f-Rzp)>0ZG&a@+Qau?s`XW6c_QqqmOSUGG-OR`gNRfS%@r)p@v1#bJySg6vW2BYddRaH&'
        'QA|)+Mxxk*$-3o*JRjd2UN|Y{HeUPu?a|?j@wwqu_f_NDwa@9MPtX5{QYd_N8c&~39@aa)q}`Y){kUQp|LNH1=O^*ObO%{htzsiJ'
        'ZFGK1u~3M+=iiveWc#Msg^{vmhpAV&0hM&Xo!IKn*9I{4Y8?RI##Vo^Hh`&DIRMoZKpR_KSsTFgtF1_J+366zx%J#sr+R;lS2DM5'
        'ZZV%XXUvy~gRh!Rvt|Cm{FV8?GUZ3vK7RhM@$+%ggXjMSKQEuZfuHcpch3JUz4$x)XrBLj`uY#_@sIRzlRo~5KK_|L{)ImNl|KFr'
        'KPV%2{uX}uiMiwazvJIwt;1K)LPTS@`SS49juHQlF@lbXYbE}fzG`26!c+9>dZ*~m79Vzs{^rX>+N3@|6f{m{7w)d{mO8io4{0Sl'
        '_zz?N00'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
